import Foundation

/// Доп. переводы названий стран и столиц для языков de, fr, it, pl, nl, pt (в JSON БД их нет).
struct CountryNameLocalization {
    private static let filename = "CountryLocalizationExtra"
    private static var cache: [String: LangData] = [:]
    private static let queue = DispatchQueue(label: "CountryNameLocalization")
    
    struct LangData {
        let names: [String: String]
        let capitals: [String: String]
    }
    
    static func countryName(for code: String, language: String) -> String? {
        let lang = language.prefix(2).lowercased()
        guard ["de", "fr", "it", "pl", "nl", "pt"].contains(lang) else { return nil }
        return queue.sync { loadIfNeeded(lang: String(lang)) }.names[code.uppercased()]
    }
    
    static func capitalName(for code: String, language: String) -> String? {
        let lang = language.prefix(2).lowercased()
        guard ["de", "fr", "it", "pl", "nl", "pt"].contains(lang) else { return nil }
        return queue.sync { loadIfNeeded(lang: String(lang)) }.capitals[code.uppercased()]
    }
    
    private static func loadIfNeeded(lang: String) -> LangData {
        if let cached = cache[lang] { return cached }
        let data = loadFromBundle(lang: lang)
        cache[lang] = data
        return data
    }
    
    private static func loadFromBundle(lang: String) -> LangData {
        if let builtin = builtinData(for: lang) { return builtin }
        if let url = Bundle.main.url(forResource: filename, withExtension: "json"),
           let data = try? Data(contentsOf: url),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let langObj = json[lang] as? [String: [String: String]],
           let names = langObj["names"],
           let capitals = langObj["capitals"], !names.isEmpty {
            return LangData(names: names, capitals: capitals)
        }
        return LangData(names: fallbackEnNames, capitals: fallbackEnCapitals)
    }
    
    private static func builtinData(for lang: String) -> LangData? {
        switch lang {
        case "de": return LangData(names: germanNames, capitals: germanCapitals)
        case "fr": return LangData(names: frenchNames, capitals: frenchCapitals)
        case "it": return LangData(names: italianNames, capitals: italianCapitals)
        case "pl": return LangData(names: polishNames, capitals: polishCapitals)
        case "nl": return LangData(names: dutchNames, capitals: dutchCapitals)
        case "pt": return LangData(names: portugueseNames, capitals: portugueseCapitals)
        default: return nil
        }
    }
}

// MARK: - Inline fallback (если JSON нет — для de, fr, it, pl, nl, pt даёт английский из встроенной таблицы)
private extension CountryNameLocalization {
    static let fallbackEnNames: [String: String] = [
        "AT": "Austria", "AL": "Albania", "AD": "Andorra", "AM": "Armenia", "AZ": "Azerbaijan",
        "BY": "Belarus", "BE": "Belgium", "BA": "Bosnia and Herzegovina", "BG": "Bulgaria",
        "HR": "Croatia", "CY": "Cyprus", "CZ": "Czech Republic", "DK": "Denmark", "EE": "Estonia",
        "FI": "Finland", "FR": "France", "GE": "Georgia", "DE": "Germany", "GR": "Greece",
        "HU": "Hungary", "IS": "Iceland", "IE": "Ireland", "IT": "Italy", "XK": "Kosovo",
        "LV": "Latvia", "LI": "Liechtenstein", "LT": "Lithuania", "LU": "Luxembourg",
        "MT": "Malta", "MD": "Moldova", "MC": "Monaco", "ME": "Montenegro", "NL": "Netherlands",
        "MK": "North Macedonia", "NO": "Norway", "PL": "Poland", "PT": "Portugal", "RO": "Romania",
        "RU": "Russia", "SM": "San Marino", "RS": "Serbia", "SK": "Slovakia", "SI": "Slovenia",
        "ES": "Spain", "SE": "Sweden", "CH": "Switzerland", "TR": "Turkey", "UA": "Ukraine",
        "GB": "United Kingdom", "VA": "Vatican City",
        "AF": "Afghanistan", "BH": "Bahrain", "BD": "Bangladesh", "BT": "Bhutan", "BN": "Brunei",
        "KH": "Cambodia", "CN": "China", "IN": "India", "ID": "Indonesia", "IR": "Iran",
        "IQ": "Iraq", "IL": "Israel", "JP": "Japan", "JO": "Jordan", "KZ": "Kazakhstan",
        "KW": "Kuwait", "KG": "Kyrgyzstan", "LA": "Laos", "LB": "Lebanon", "MY": "Malaysia",
        "MV": "Maldives", "MN": "Mongolia", "MM": "Myanmar", "NP": "Nepal", "OM": "Oman",
        "PK": "Pakistan", "PH": "Philippines", "QA": "Qatar", "SA": "Saudi Arabia", "SG": "Singapore",
        "LK": "Sri Lanka", "SY": "Syria", "TW": "Taiwan", "TJ": "Tajikistan", "TH": "Thailand",
        "TL": "Timor-Leste", "AE": "United Arab Emirates", "UZ": "Uzbekistan", "VN": "Vietnam", "YE": "Yemen",
        "KP": "North Korea", "PS": "Palestine", "TM": "Turkmenistan", "KR": "South Korea",
        "DZ": "Algeria", "AO": "Angola", "BJ": "Benin", "BW": "Botswana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Cameroon", "CV": "Cape Verde", "CF": "Central African Republic",
        "TD": "Chad", "KM": "Comoros", "CG": "Republic of the Congo", "CD": "Democratic Republic of the Congo",
        "CI": "Ivory Coast", "DJ": "Djibouti", "EG": "Egypt", "GQ": "Equatorial Guinea", "ER": "Eritrea",
        "ET": "Ethiopia", "GA": "Gabon", "GM": "Gambia", "GH": "Ghana", "GN": "Guinea",
        "GW": "Guinea-Bissau", "KE": "Kenya", "LS": "Lesotho", "LR": "Liberia", "LY": "Libya",
        "MG": "Madagascar", "MW": "Malawi", "ML": "Mali", "MR": "Mauritania", "MU": "Mauritius",
        "MA": "Morocco", "MZ": "Mozambique", "NA": "Namibia", "NE": "Niger", "NG": "Nigeria",
        "RW": "Rwanda", "ST": "São Tomé and Príncipe", "SN": "Senegal", "SC": "Seychelles",
        "SL": "Sierra Leone", "SO": "Somalia", "ZA": "South Africa", "SS": "South Sudan",
        "SD": "Sudan", "SZ": "Eswatini", "TZ": "Tanzania", "TG": "Togo", "TN": "Tunisia",
        "UG": "Uganda", "ZM": "Zambia", "ZW": "Zimbabwe",
        "AR": "Argentina", "BO": "Bolivia", "BR": "Brazil", "CL": "Chile", "CO": "Colombia",
        "EC": "Ecuador", "GY": "Guyana", "PY": "Paraguay", "PE": "Peru", "SR": "Suriname",
        "UY": "Uruguay", "VE": "Venezuela", "CA": "Canada", "MX": "Mexico", "US": "United States",
        "AG": "Antigua and Barbuda", "BS": "Bahamas", "BB": "Barbados", "BZ": "Belize",
        "CR": "Costa Rica", "CU": "Cuba", "DM": "Dominica", "DO": "Dominican Republic",
        "SV": "El Salvador", "GD": "Grenada", "GT": "Guatemala", "HT": "Haiti", "HN": "Honduras",
        "JM": "Jamaica", "NI": "Nicaragua", "PA": "Panama", "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia", "VC": "Saint Vincent and the Grenadines", "TT": "Trinidad and Tobago",
        "AU": "Australia", "FJ": "Fiji", "KI": "Kiribati", "MH": "Marshall Islands",
        "FM": "Micronesia", "NR": "Nauru", "NZ": "New Zealand", "PW": "Palau", "PG": "Papua New Guinea",
        "WS": "Samoa", "SB": "Solomon Islands", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let fallbackEnCapitals: [String: String] = [
        "AT": "Vienna", "AL": "Tirana", "AD": "Andorra la Vella", "AM": "Yerevan", "AZ": "Baku",
        "BY": "Minsk", "BE": "Brussels", "BA": "Sarajevo", "BG": "Sofia", "HR": "Zagreb",
        "CY": "Nicosia", "CZ": "Prague", "DK": "Copenhagen", "EE": "Tallinn", "FI": "Helsinki",
        "FR": "Paris", "GE": "Tbilisi", "DE": "Berlin", "GR": "Athens", "HU": "Budapest",
        "IS": "Reykjavik", "IE": "Dublin", "IT": "Rome", "XK": "Pristina", "LV": "Riga",
        "LI": "Vaduz", "LT": "Vilnius", "LU": "Luxembourg", "MT": "Valletta", "MD": "Chisinau",
        "MC": "Monaco", "ME": "Podgorica", "NL": "Amsterdam", "MK": "Skopje", "NO": "Oslo",
        "PL": "Warsaw", "PT": "Lisbon", "RO": "Bucharest", "RU": "Moscow", "SM": "San Marino",
        "RS": "Belgrade", "SK": "Bratislava", "SI": "Ljubljana", "ES": "Madrid", "SE": "Stockholm",
        "CH": "Bern", "TR": "Ankara", "UA": "Kyiv", "GB": "London", "VA": "Vatican City"
    ]
    
    // MARK: - German (de)
    static let germanNames: [String: String] = [
        "AT": "Österreich", "AL": "Albanien", "AD": "Andorra", "AM": "Armenien", "AZ": "Aserbaidschan",
        "BY": "Belarus", "BE": "Belgien", "BA": "Bosnien und Herzegowina", "BG": "Bulgarien",
        "HR": "Kroatien", "CY": "Zypern", "CZ": "Tschechien", "DK": "Dänemark", "EE": "Estland",
        "FI": "Finnland", "FR": "Frankreich", "GE": "Georgien", "DE": "Deutschland", "GR": "Griechenland",
        "HU": "Ungarn", "IS": "Island", "IE": "Irland", "IT": "Italien", "XK": "Kosovo",
        "LV": "Lettland", "LI": "Liechtenstein", "LT": "Litauen", "LU": "Luxemburg",
        "MT": "Malta", "MD": "Moldau", "MC": "Monaco", "ME": "Montenegro", "NL": "Niederlande",
        "MK": "Nordmazedonien", "NO": "Norwegen", "PL": "Polen", "PT": "Portugal", "RO": "Rumänien",
        "RU": "Russland", "SM": "San Marino", "RS": "Serbien", "SK": "Slowakei", "SI": "Slowenien",
        "ES": "Spanien", "SE": "Schweden", "CH": "Schweiz", "TR": "Türkei", "UA": "Ukraine",
        "GB": "Vereinigtes Königreich", "VA": "Vatikanstadt",
        "AF": "Afghanistan", "BH": "Bahrain", "BD": "Bangladesch", "BT": "Bhutan", "BN": "Brunei",
        "KH": "Kambodscha", "CN": "China", "IN": "Indien", "ID": "Indonesien", "IR": "Iran",
        "IQ": "Irak", "IL": "Israel", "JP": "Japan", "JO": "Jordanien", "KZ": "Kasachstan",
        "KW": "Kuwait", "KG": "Kirgisistan", "LA": "Laos", "LB": "Libanon", "MY": "Malaysia",
        "MV": "Malediven", "MN": "Mongolei", "MM": "Myanmar", "NP": "Nepal", "OM": "Oman",
        "PK": "Pakistan", "PH": "Philippinen", "QA": "Katar", "SA": "Saudi-Arabien", "SG": "Singapur",
        "LK": "Sri Lanka", "SY": "Syrien", "TW": "Taiwan", "TJ": "Tadschikistan", "TH": "Thailand",
        "TL": "Osttimor", "AE": "Vereinigte Arabische Emirate", "UZ": "Usbekistan", "VN": "Vietnam", "YE": "Jemen",
        "KP": "Nordkorea", "PS": "Palästina", "TM": "Turkmenistan", "KR": "Südkorea",
        "DZ": "Algerien", "AO": "Angola", "BJ": "Benin", "BW": "Botswana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Kamerun", "CV": "Kap Verde", "CF": "Zentralafrikanische Republik",
        "TD": "Tschad", "KM": "Komoren", "CG": "Kongo", "CD": "Demokratische Republik Kongo",
        "CI": "Elfenbeinküste", "DJ": "Dschibuti", "EG": "Ägypten", "GQ": "Äquatorialguinea", "ER": "Eritrea",
        "ET": "Äthiopien", "GA": "Gabun", "GM": "Gambia", "GH": "Ghana", "GN": "Guinea",
        "GW": "Guinea-Bissau", "KE": "Kenia", "LS": "Lesotho", "LR": "Liberia", "LY": "Libyen",
        "MG": "Madagaskar", "MW": "Malawi", "ML": "Mali", "MR": "Mauretanien", "MU": "Mauritius",
        "MA": "Marokko", "MZ": "Mosambik", "NA": "Namibia", "NE": "Niger", "NG": "Nigeria",
        "RW": "Ruanda", "ST": "São Tomé und Príncipe", "SN": "Senegal", "SC": "Seychellen",
        "SL": "Sierra Leone", "SO": "Somalia", "ZA": "Südafrika", "SS": "Sudsudan",
        "SD": "Sudan", "SZ": "Eswatini", "TZ": "Tansania", "TG": "Togo", "TN": "Tunesien",
        "UG": "Uganda", "ZM": "Sambia", "ZW": "Simbabwe",
        "AR": "Argentinien", "BO": "Bolivien", "BR": "Brasilien", "CL": "Chile", "CO": "Kolumbien",
        "EC": "Ecuador", "GY": "Guyana", "PY": "Paraguay", "PE": "Peru", "SR": "Suriname",
        "UY": "Uruguay", "VE": "Venezuela", "CA": "Kanada", "MX": "Mexiko", "US": "Vereinigte Staaten",
        "AG": "Antigua und Barbuda", "BS": "Bahamas", "BB": "Barbados", "BZ": "Belize",
        "CR": "Costa Rica", "CU": "Kuba", "DM": "Dominica", "DO": "Dominikanische Republik",
        "SV": "El Salvador", "GD": "Grenada", "GT": "Guatemala", "HT": "Haiti", "HN": "Honduras",
        "JM": "Jamaika", "NI": "Nicaragua", "PA": "Panama", "KN": "St. Kitts und Nevis",
        "LC": "St. Lucia", "VC": "St. Vincent und die Grenadinen", "TT": "Trinidad und Tobago",
        "AU": "Australien", "FJ": "Fidschi", "KI": "Kiribati", "MH": "Marshallinseln",
        "FM": "Mikronesien", "NR": "Nauru", "NZ": "Neuseeland", "PW": "Palau", "PG": "Papua-Neuguinea",
        "WS": "Samoa", "SB": "Salomonen", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let germanCapitals: [String: String] = [
        "AT": "Wien", "AL": "Tirana", "AD": "Andorra la Vella", "AM": "Eriwan", "AZ": "Baku",
        "BY": "Minsk", "BE": "Brüssel", "BA": "Sarajevo", "BG": "Sofia", "HR": "Zagreb",
        "CY": "Nikosia", "CZ": "Prag", "DK": "Kopenhagen", "EE": "Tallinn", "FI": "Helsinki",
        "FR": "Paris", "GE": "Tiflis", "DE": "Berlin", "GR": "Athen", "HU": "Budapest",
        "IS": "Reykjavík", "IE": "Dublin", "IT": "Rom", "XK": "Pristina", "LV": "Riga",
        "LI": "Vaduz", "LT": "Vilnius", "LU": "Luxemburg", "MT": "Valletta", "MD": "Chișinău",
        "MC": "Monaco", "ME": "Podgorica", "NL": "Amsterdam", "MK": "Skopje", "NO": "Oslo",
        "PL": "Warschau", "PT": "Lissabon", "RO": "Bukarest", "RU": "Moskau", "SM": "San Marino",
        "RS": "Belgrad", "SK": "Bratislava", "SI": "Ljubljana", "ES": "Madrid", "SE": "Stockholm",
        "CH": "Bern", "TR": "Ankara", "UA": "Kiew", "GB": "London", "VA": "Vatikanstadt",
        "AF": "Kabul", "BH": "Manama", "BD": "Dhaka", "BT": "Thimphu", "BN": "Bandar Seri Begawan",
        "KH": "Phnom Penh", "CN": "Peking", "IN": "Neu-Delhi", "ID": "Jakarta", "IR": "Teheran",
        "IQ": "Bagdad", "IL": "Jerusalem", "JP": "Tokio", "JO": "Amman", "KZ": "Astana",
        "KW": "Kuwait-Stadt", "KG": "Bischkek", "LA": "Vientiane", "LB": "Beirut", "MY": "Kuala Lumpur",
        "MV": "Malé", "MN": "Ulaanbaatar", "MM": "Naypyidaw", "NP": "Kathmandu", "OM": "Maskat",
        "PK": "Islamabad", "PH": "Manila", "QA": "Doha", "SA": "Riad", "SG": "Singapur",
        "LK": "Colombo", "SY": "Damaskus", "TW": "Taipeh", "TJ": "Duschanbe", "TH": "Bangkok",
        "TL": "Dili", "AE": "Abu Dhabi", "UZ": "Taschkent", "VN": "Hanoi", "YE": "Sanaa",
        "KP": "Pjöngjang", "PS": "Ramallah", "TM": "Aschgabat", "KR": "Seoul",
        "DZ": "Algier", "AO": "Luanda", "BJ": "Porto-Novo", "BW": "Gaborone", "BF": "Ouagadougou",
        "BI": "Gitega", "CM": "Jaunde", "CV": "Praia", "CF": "Bangui", "TD": "N’Djamena",
        "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "CI": "Yamoussoukro", "DJ": "Dschibuti",
        "EG": "Kairo", "GQ": "Malabo", "ER": "Asmara", "ET": "Addis Abeba", "GA": "Libreville",
        "GM": "Banjul", "GH": "Accra", "GN": "Conakry", "GW": "Bissau", "KE": "Nairobi",
        "LS": "Maseru", "LR": "Monrovia", "LY": "Tripolis", "MG": "Antananarivo", "MW": "Lilongwe",
        "ML": "Bamako", "MR": "Nouakchott", "MU": "Port Louis", "MA": "Rabat", "MZ": "Maputo",
        "NA": "Windhoek", "NE": "Niamey", "NG": "Abuja", "RW": "Kigali", "ST": "São Tomé",
        "SN": "Dakar", "SC": "Victoria", "SL": "Freetown", "SO": "Mogadischu", "ZA": "Pretoria",
        "SS": "Juba", "SD": "Khartum", "SZ": "Mbabane", "TZ": "Dodoma", "TG": "Lomé",
        "TN": "Tunis", "UG": "Kampala", "ZM": "Lusaka", "ZW": "Harare",
        "AR": "Buenos Aires", "BO": "Sucre", "BR": "Brasília", "CL": "Santiago", "CO": "Bogotá",
        "EC": "Quito", "GY": "Georgetown", "PY": "Asunción", "PE": "Lima", "SR": "Paramaribo",
        "UY": "Montevideo", "VE": "Caracas", "CA": "Ottawa", "MX": "Mexiko-Stadt", "US": "Washington D.C.",
        "AG": "St. John’s", "BS": "Nassau", "BB": "Bridgetown", "BZ": "Belmopan", "CR": "San José",
        "CU": "Havanna", "DM": "Roseau", "DO": "Santo Domingo", "SV": "San Salvador", "GD": "St. George’s",
        "GT": "Guatemala-Stadt", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "JM": "Kingston",
        "NI": "Managua", "PA": "Panama-Stadt", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown", "TT": "Port of Spain",
        "AU": "Canberra", "FJ": "Suva", "KI": "South Tarawa", "MH": "Majuro", "FM": "Palikir",
        "NR": "Yaren", "NZ": "Wellington", "PW": "Ngerulmud", "PG": "Port Moresby", "WS": "Apia",
        "SB": "Honiara", "TO": "Nukuʻalofa", "TV": "Funafuti", "VU": "Port Vila"
    ]
    
    // MARK: - French (fr)
    static let frenchNames: [String: String] = [
        "AT": "Autriche", "AL": "Albanie", "AD": "Andorre", "AM": "Arménie", "AZ": "Azerbaïdjan",
        "BY": "Biélorussie", "BE": "Belgique", "BA": "Bosnie-Herzégovine", "BG": "Bulgarie",
        "HR": "Croatie", "CY": "Chypre", "CZ": "Tchéquie", "DK": "Danemark", "EE": "Estonie",
        "FI": "Finlande", "FR": "France", "GE": "Géorgie", "DE": "Allemagne", "GR": "Grèce",
        "HU": "Hongrie", "IS": "Islande", "IE": "Irlande", "IT": "Italie", "XK": "Kosovo",
        "LV": "Lettonie", "LI": "Liechtenstein", "LT": "Lituanie", "LU": "Luxembourg",
        "MT": "Malte", "MD": "Moldavie", "MC": "Monaco", "ME": "Monténégro", "NL": "Pays-Bas",
        "MK": "Macédoine du Nord", "NO": "Norvège", "PL": "Pologne", "PT": "Portugal", "RO": "Roumanie",
        "RU": "Russie", "SM": "Saint-Marin", "RS": "Serbie", "SK": "Slovaquie", "SI": "Slovénie",
        "ES": "Espagne", "SE": "Suède", "CH": "Suisse", "TR": "Turquie", "UA": "Ukraine",
        "GB": "Royaume-Uni", "VA": "Vatican",
        "AF": "Afghanistan", "BH": "Bahreïn", "BD": "Bangladesh", "BT": "Bhoutan", "BN": "Brunei",
        "KH": "Cambodge", "CN": "Chine", "IN": "Inde", "ID": "Indonésie", "IR": "Iran",
        "IQ": "Irak", "IL": "Israël", "JP": "Japon", "JO": "Jordanie", "KZ": "Kazakhstan",
        "KW": "Koweït", "KG": "Kirghizistan", "LA": "Laos", "LB": "Liban", "MY": "Malaisie",
        "MV": "Maldives", "MN": "Mongolie", "MM": "Myanmar", "NP": "Népal", "OM": "Oman",
        "PK": "Pakistan", "PH": "Philippines", "QA": "Qatar", "SA": "Arabie saoudite", "SG": "Singapour",
        "LK": "Sri Lanka", "SY": "Syrie", "TW": "Taïwan", "TJ": "Tadjikistan", "TH": "Thaïlande",
        "TL": "Timor oriental", "AE": "Émirats arabes unis", "UZ": "Ouzbékistan", "VN": "Viêt Nam", "YE": "Yémen",
        "KP": "Corée du Nord", "PS": "Palestine", "TM": "Turkménistan", "KR": "Corée du Sud",
        "DZ": "Algérie", "AO": "Angola", "BJ": "Bénin", "BW": "Botswana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Cameroun", "CV": "Cap-Vert", "CF": "République centrafricaine",
        "TD": "Tchad", "KM": "Comores", "CG": "Congo", "CD": "République démocratique du Congo",
        "CI": "Côte d'Ivoire", "DJ": "Djibouti", "EG": "Égypte", "GQ": "Guinée équatoriale", "ER": "Érythrée",
        "ET": "Éthiopie", "GA": "Gabon", "GM": "Gambie", "GH": "Ghana", "GN": "Guinée",
        "GW": "Guinée-Bissau", "KE": "Kenya", "LS": "Lesotho", "LR": "Liberia", "LY": "Libye",
        "MG": "Madagascar", "MW": "Malawi", "ML": "Mali", "MR": "Mauritanie", "MU": "Maurice",
        "MA": "Maroc", "MZ": "Mozambique", "NA": "Namibie", "NE": "Niger", "NG": "Nigeria",
        "RW": "Rwanda", "ST": "Sao Tomé-et-Príncipe", "SN": "Sénégal", "SC": "Seychelles",
        "SL": "Sierra Leone", "SO": "Somalie", "ZA": "Afrique du Sud", "SS": "Soudan du Sud",
        "SD": "Soudan", "SZ": "Eswatini", "TZ": "Tanzanie", "TG": "Togo", "TN": "Tunisie",
        "UG": "Ouganda", "ZM": "Zambie", "ZW": "Zimbabwe",
        "AR": "Argentine", "BO": "Bolivie", "BR": "Brésil", "CL": "Chili", "CO": "Colombie",
        "EC": "Équateur", "GY": "Guyana", "PY": "Paraguay", "PE": "Pérou", "SR": "Suriname",
        "UY": "Uruguay", "VE": "Venezuela", "CA": "Canada", "MX": "Mexique", "US": "États-Unis",
        "AG": "Antigua-et-Barbuda", "BS": "Bahamas", "BB": "Barbade", "BZ": "Belize",
        "CR": "Costa Rica", "CU": "Cuba", "DM": "Dominique", "DO": "République dominicaine",
        "SV": "Salvador", "GD": "Grenade", "GT": "Guatemala", "HT": "Haïti", "HN": "Honduras",
        "JM": "Jamaïque", "NI": "Nicaragua", "PA": "Panama", "KN": "Saint-Christophe-et-Niévès",
        "LC": "Sainte-Lucie", "VC": "Saint-Vincent-et-les-Grenadines", "TT": "Trinité-et-Tobago",
        "AU": "Australie", "FJ": "Fidji", "KI": "Kiribati", "MH": "Îles Marshall",
        "FM": "Micronésie", "NR": "Nauru", "NZ": "Nouvelle-Zélande", "PW": "Palaos", "PG": "Papouasie-Nouvelle-Guinée",
        "WS": "Samoa", "SB": "Îles Salomon", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let frenchCapitals: [String: String] = [
        "AT": "Vienne", "AL": "Tirana", "AD": "Andorre-la-Vieille", "AM": "Erevan", "AZ": "Bakou",
        "BY": "Minsk", "BE": "Bruxelles", "BA": "Sarajevo", "BG": "Sofia", "HR": "Zagreb",
        "CY": "Nicosie", "CZ": "Prague", "DK": "Copenhague", "EE": "Tallinn", "FI": "Helsinki",
        "FR": "Paris", "GE": "Tbilissi", "DE": "Berlin", "GR": "Athènes", "HU": "Budapest",
        "IS": "Reykjavik", "IE": "Dublin", "IT": "Rome", "XK": "Pristina", "LV": "Riga",
        "LI": "Vaduz", "LT": "Vilnius", "LU": "Luxembourg", "MT": "La Valette", "MD": "Chișinău",
        "MC": "Monaco", "ME": "Podgorica", "NL": "Amsterdam", "MK": "Skopje", "NO": "Oslo",
        "PL": "Varsovie", "PT": "Lisbonne", "RO": "Bucarest", "RU": "Moscou", "SM": "Saint-Marin",
        "RS": "Belgrade", "SK": "Bratislava", "SI": "Ljubljana", "ES": "Madrid", "SE": "Stockholm",
        "CH": "Berne", "TR": "Ankara", "UA": "Kiev", "GB": "Londres", "VA": "Vatican",
        "AF": "Kaboul", "BH": "Manama", "BD": "Dacca", "BT": "Thimphou", "BN": "Bandar Seri Begawan",
        "KH": "Phnom Penh", "CN": "Pékin", "IN": "New Delhi", "ID": "Jakarta", "IR": "Téhéran",
        "IQ": "Bagdad", "IL": "Jérusalem", "JP": "Tokyo", "JO": "Amman", "KZ": "Astana",
        "KW": "Koweït", "KG": "Bichkek", "LA": "Vientiane", "LB": "Beyrouth", "MY": "Kuala Lumpur",
        "MV": "Malé", "MN": "Oulan-Bator", "MM": "Naypyidaw", "NP": "Katmandou", "OM": "Mascate",
        "PK": "Islamabad", "PH": "Manille", "QA": "Doha", "SA": "Riyad", "SG": "Singapour",
        "LK": "Colombo", "SY": "Damas", "TW": "Taipei", "TJ": "Douchanbé", "TH": "Bangkok",
        "TL": "Dili", "AE": "Abou Dhabi", "UZ": "Tachkent", "VN": "Hanoï", "YE": "Sanaa",
        "KP": "Pyongyang", "PS": "Ramallah", "TM": "Achgabat", "KR": "Séoul",
        "DZ": "Alger", "AO": "Luanda", "BJ": "Porto-Novo", "BW": "Gaborone", "BF": "Ouagadougou",
        "BI": "Gitega", "CM": "Yaoundé", "CV": "Praia", "CF": "Bangui", "TD": "N'Djamena",
        "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "CI": "Yamoussoukro", "DJ": "Djibouti",
        "EG": "Le Caire", "GQ": "Malabo", "ER": "Asmara", "ET": "Addis-Abeba", "GA": "Libreville",
        "GM": "Banjul", "GH": "Accra", "GN": "Conakry", "GW": "Bissau", "KE": "Nairobi",
        "LS": "Maseru", "LR": "Monrovia", "LY": "Tripoli", "MG": "Antananarivo", "MW": "Lilongwe",
        "ML": "Bamako", "MR": "Nouakchott", "MU": "Port-Louis", "MA": "Rabat", "MZ": "Maputo",
        "NA": "Windhoek", "NE": "Niamey", "NG": "Abuja", "RW": "Kigali", "ST": "São Tomé",
        "SN": "Dakar", "SC": "Victoria", "SL": "Freetown", "SO": "Mogadiscio", "ZA": "Pretoria",
        "SS": "Djouba", "SD": "Khartoum", "SZ": "Mbabane", "TZ": "Dodoma", "TG": "Lomé",
        "TN": "Tunis", "UG": "Kampala", "ZM": "Lusaka", "ZW": "Harare",
        "AR": "Buenos Aires", "BO": "Sucre", "BR": "Brasília", "CL": "Santiago", "CO": "Bogota",
        "EC": "Quito", "GY": "Georgetown", "PY": "Asunción", "PE": "Lima", "SR": "Paramaribo",
        "UY": "Montevideo", "VE": "Caracas", "CA": "Ottawa", "MX": "Mexico", "US": "Washington D.C.",
        "AG": "Saint John's", "BS": "Nassau", "BB": "Bridgetown", "BZ": "Belmopan", "CR": "San José",
        "CU": "La Havane", "DM": "Roseau", "DO": "Saint-Domingue", "SV": "San Salvador", "GD": "Saint George's",
        "GT": "Guatemala", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "JM": "Kingston",
        "NI": "Managua", "PA": "Panama", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown", "TT": "Port-d'Espagne",
        "AU": "Canberra", "FJ": "Suva", "KI": "Tarawa-Sud", "MH": "Majuro", "FM": "Palikir",
        "NR": "Yaren", "NZ": "Wellington", "PW": "Ngerulmud", "PG": "Port Moresby", "WS": "Apia",
        "SB": "Honiara", "TO": "Nukuʻalofa", "TV": "Funafuti", "VU": "Port-Vila"
    ]
    
    // MARK: - Italian (it)
    static let italianNames: [String: String] = [
        "AT": "Austria", "AL": "Albania", "AD": "Andorra", "AM": "Armenia", "AZ": "Azerbaigian",
        "BY": "Bielorussia", "BE": "Belgio", "BA": "Bosnia ed Erzegovina", "BG": "Bulgaria",
        "HR": "Croazia", "CY": "Cipro", "CZ": "Repubblica Ceca", "DK": "Danimarca", "EE": "Estonia",
        "FI": "Finlandia", "FR": "Francia", "GE": "Georgia", "DE": "Germania", "GR": "Grecia",
        "HU": "Ungheria", "IS": "Islanda", "IE": "Irlanda", "IT": "Italia", "XK": "Kosovo",
        "LV": "Lettonia", "LI": "Liechtenstein", "LT": "Lituania", "LU": "Lussemburgo",
        "MT": "Malta", "MD": "Moldavia", "MC": "Monaco", "ME": "Montenegro", "NL": "Paesi Bassi",
        "MK": "Macedonia del Nord", "NO": "Norvegia", "PL": "Polonia", "PT": "Portogallo", "RO": "Romania",
        "RU": "Russia", "SM": "San Marino", "RS": "Serbia", "SK": "Slovacchia", "SI": "Slovenia",
        "ES": "Spagna", "SE": "Svezia", "CH": "Svizzera", "TR": "Turchia", "UA": "Ucraina",
        "GB": "Regno Unito", "VA": "Città del Vaticano",
        "AF": "Afghanistan", "BH": "Bahrein", "BD": "Bangladesh", "BT": "Bhutan", "BN": "Brunei",
        "KH": "Cambogia", "CN": "Cina", "IN": "India", "ID": "Indonesia", "IR": "Iran",
        "IQ": "Iraq", "IL": "Israele", "JP": "Giappone", "JO": "Giordania", "KZ": "Kazakistan",
        "KW": "Kuwait", "KG": "Kirghizistan", "LA": "Laos", "LB": "Libano", "MY": "Malesia",
        "MV": "Maldive", "MN": "Mongolia", "MM": "Myanmar", "NP": "Nepal", "OM": "Oman",
        "PK": "Pakistan", "PH": "Filippine", "QA": "Qatar", "SA": "Arabia Saudita", "SG": "Singapore",
        "LK": "Sri Lanka", "SY": "Siria", "TW": "Taiwan", "TJ": "Tagikistan", "TH": "Thailandia",
        "TL": "Timor Est", "AE": "Emirati Arabi Uniti", "UZ": "Uzbekistan", "VN": "Vietnam", "YE": "Yemen",
        "KP": "Corea del Nord", "PS": "Palestina", "TM": "Turkmenistan", "KR": "Corea del Sud",
        "DZ": "Algeria", "AO": "Angola", "BJ": "Benin", "BW": "Botswana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Camerun", "CV": "Capo Verde", "CF": "Rep. Centrafricana",
        "TD": "Ciad", "KM": "Comore", "CG": "Congo", "CD": "Rep. Dem. del Congo",
        "CI": "Costa d'Avorio", "DJ": "Gibuti", "EG": "Egitto", "GQ": "Guinea Equatoriale", "ER": "Eritrea",
        "ET": "Etiopia", "GA": "Gabon", "GM": "Gambia", "GH": "Ghana", "GN": "Guinea",
        "GW": "Guinea-Bissau", "KE": "Kenya", "LS": "Lesotho", "LR": "Liberia", "LY": "Libia",
        "MG": "Madagascar", "MW": "Malawi", "ML": "Mali", "MR": "Mauritania", "MU": "Mauritius",
        "MA": "Marocco", "MZ": "Mozambico", "NA": "Namibia", "NE": "Niger", "NG": "Nigeria",
        "RW": "Ruanda", "ST": "São Tomé e Príncipe", "SN": "Senegal", "SC": "Seychelles",
        "SL": "Sierra Leone", "SO": "Somalia", "ZA": "Sudafrica", "SS": "Sudan del Sud",
        "SD": "Sudan", "SZ": "Eswatini", "TZ": "Tanzania", "TG": "Togo", "TN": "Tunisia",
        "UG": "Uganda", "ZM": "Zambia", "ZW": "Zimbabwe",
        "AR": "Argentina", "BO": "Bolivia", "BR": "Brasile", "CL": "Cile", "CO": "Colombia",
        "EC": "Ecuador", "GY": "Guyana", "PY": "Paraguay", "PE": "Perù", "SR": "Suriname",
        "UY": "Uruguay", "VE": "Venezuela", "CA": "Canada", "MX": "Messico", "US": "Stati Uniti",
        "AG": "Antigua e Barbuda", "BS": "Bahamas", "BB": "Barbados", "BZ": "Belize",
        "CR": "Costa Rica", "CU": "Cuba", "DM": "Dominica", "DO": "Rep. Dominicana",
        "SV": "El Salvador", "GD": "Grenada", "GT": "Guatemala", "HT": "Haiti", "HN": "Honduras",
        "JM": "Giamaica", "NI": "Nicaragua", "PA": "Panama", "KN": "Saint Kitts e Nevis",
        "LC": "Santa Lucia", "VC": "Saint Vincent e Grenadine", "TT": "Trinidad e Tobago",
        "AU": "Australia", "FJ": "Figi", "KI": "Kiribati", "MH": "Isole Marshall",
        "FM": "Micronesia", "NR": "Nauru", "NZ": "Nuova Zelanda", "PW": "Palau", "PG": "Papua Nuova Guinea",
        "WS": "Samoa", "SB": "Isole Salomone", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let italianCapitals: [String: String] = [
        "AT": "Vienna", "AL": "Tirana", "AD": "Andorra la Vella", "AM": "Erevan", "AZ": "Baku",
        "BY": "Minsk", "BE": "Bruxelles", "BA": "Sarajevo", "BG": "Sofia", "HR": "Zagabria",
        "CY": "Nicosia", "CZ": "Praga", "DK": "Copenaghen", "EE": "Tallinn", "FI": "Helsinki",
        "FR": "Parigi", "GE": "Tbilisi", "DE": "Berlino", "GR": "Atene", "HU": "Budapest",
        "IS": "Reykjavík", "IE": "Dublino", "IT": "Roma", "XK": "Pristina", "LV": "Riga",
        "LI": "Vaduz", "LT": "Vilnius", "LU": "Lussemburgo", "MT": "La Valletta", "MD": "Chișinău",
        "MC": "Monaco", "ME": "Podgorica", "NL": "Amsterdam", "MK": "Skopje", "NO": "Oslo",
        "PL": "Varsavia", "PT": "Lisbona", "RO": "Bucarest", "RU": "Mosca", "SM": "San Marino",
        "RS": "Belgrado", "SK": "Bratislava", "SI": "Lubiana", "ES": "Madrid", "SE": "Stoccolma",
        "CH": "Berna", "TR": "Ankara", "UA": "Kiev", "GB": "Londra", "VA": "Città del Vaticano",
        "AF": "Kabul", "BH": "Manama", "BD": "Dacca", "BT": "Thimphu", "BN": "Bandar Seri Begawan",
        "KH": "Phnom Penh", "CN": "Pechino", "IN": "Nuova Delhi", "ID": "Giacarta", "IR": "Teheran",
        "IQ": "Baghdad", "IL": "Gerusalemme", "JP": "Tokyo", "JO": "Amman", "KZ": "Astana",
        "KW": "Kuwait", "KG": "Bishkek", "LA": "Vientiane", "LB": "Beirut", "MY": "Kuala Lumpur",
        "MV": "Malé", "MN": "Ulaanbaatar", "MM": "Naypyidaw", "NP": "Kathmandu", "OM": "Mascate",
        "PK": "Islamabad", "PH": "Manila", "QA": "Doha", "SA": "Riyad", "SG": "Singapore",
        "LK": "Colombo", "SY": "Damasco", "TW": "Taipei", "TJ": "Dushanbe", "TH": "Bangkok",
        "TL": "Dili", "AE": "Abu Dhabi", "UZ": "Tashkent", "VN": "Hanoi", "YE": "Sana'a",
        "KP": "Pyongyang", "PS": "Ramallah", "TM": "Ashgabat", "KR": "Seul",
        "DZ": "Algeri", "AO": "Luanda", "BJ": "Porto-Novo", "BW": "Gaborone", "BF": "Ouagadougou",
        "BI": "Gitega", "CM": "Yaoundé", "CV": "Praia", "CF": "Bangui", "TD": "N'Djamena",
        "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "CI": "Yamoussoukro", "DJ": "Gibuti",
        "EG": "Il Cairo", "GQ": "Malabo", "ER": "Asmara", "ET": "Addis Abeba", "GA": "Libreville",
        "GM": "Banjul", "GH": "Accra", "GN": "Conakry", "GW": "Bissau", "KE": "Nairobi",
        "LS": "Maseru", "LR": "Monrovia", "LY": "Tripoli", "MG": "Antananarivo", "MW": "Lilongwe",
        "ML": "Bamako", "MR": "Nouakchott", "MU": "Port Louis", "MA": "Rabat", "MZ": "Maputo",
        "NA": "Windhoek", "NE": "Niamey", "NG": "Abuja", "RW": "Kigali", "ST": "São Tomé",
        "SN": "Dakar", "SC": "Victoria", "SL": "Freetown", "SO": "Mogadiscio", "ZA": "Pretoria",
        "SS": "Juba", "SD": "Khartum", "SZ": "Mbabane", "TZ": "Dodoma", "TG": "Lomé",
        "TN": "Tunisi", "UG": "Kampala", "ZM": "Lusaka", "ZW": "Harare",
        "AR": "Buenos Aires", "BO": "Sucre", "BR": "Brasília", "CL": "Santiago", "CO": "Bogotá",
        "EC": "Quito", "GY": "Georgetown", "PY": "Asunción", "PE": "Lima", "SR": "Paramaribo",
        "UY": "Montevideo", "VE": "Caracas", "CA": "Ottawa", "MX": "Città del Messico", "US": "Washington D.C.",
        "AG": "Saint John's", "BS": "Nassau", "BB": "Bridgetown", "BZ": "Belmopan", "CR": "San José",
        "CU": "L'Avana", "DM": "Roseau", "DO": "Santo Domingo", "SV": "San Salvador", "GD": "Saint George's",
        "GT": "Città del Guatemala", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "JM": "Kingston",
        "NI": "Managua", "PA": "Panama", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown", "TT": "Port of Spain",
        "AU": "Canberra", "FJ": "Suva", "KI": "Tarawa Sud", "MH": "Majuro", "FM": "Palikir",
        "NR": "Yaren", "NZ": "Wellington", "PW": "Ngerulmud", "PG": "Port Moresby", "WS": "Apia",
        "SB": "Honiara", "TO": "Nukuʻalofa", "TV": "Funafuti", "VU": "Port Vila"
    ]
    
    // MARK: - Polish (pl)
    static let polishNames: [String: String] = [
        "AT": "Austria", "AL": "Albania", "AD": "Andora", "AM": "Armenia", "AZ": "Azerbejdżan",
        "BY": "Białoruś", "BE": "Belgia", "BA": "Bośnia i Hercegowina", "BG": "Bułgaria",
        "HR": "Chorwacja", "CY": "Cypr", "CZ": "Czechy", "DK": "Dania", "EE": "Estonia",
        "FI": "Finlandia", "FR": "Francja", "GE": "Gruzja", "DE": "Niemcy", "GR": "Grecja",
        "HU": "Węgry", "IS": "Islandia", "IE": "Irlandia", "IT": "Włochy", "XK": "Kosowo",
        "LV": "Łotwa", "LI": "Liechtenstein", "LT": "Litwa", "LU": "Luksemburg",
        "MT": "Malta", "MD": "Mołdawia", "MC": "Monako", "ME": "Czarnogóra", "NL": "Holandia",
        "MK": "Macedonia Północna", "NO": "Norwegia", "PL": "Polska", "PT": "Portugalia", "RO": "Rumunia",
        "RU": "Rosja", "SM": "San Marino", "RS": "Serbia", "SK": "Słowacja", "SI": "Słowenia",
        "ES": "Hiszpania", "SE": "Szwecja", "CH": "Szwajcaria", "TR": "Turcja", "UA": "Ukraina",
        "GB": "Wielka Brytania", "VA": "Watykan",
        "AF": "Afganistan", "BH": "Bahrajn", "BD": "Bangladesz", "BT": "Bhutan", "BN": "Brunei",
        "KH": "Kambodża", "CN": "Chiny", "IN": "Indie", "ID": "Indonezja", "IR": "Iran",
        "IQ": "Irak", "IL": "Izrael", "JP": "Japonia", "JO": "Jordania", "KZ": "Kazachstan",
        "KW": "Kuwejt", "KG": "Kirgistan", "LA": "Laos", "LB": "Liban", "MY": "Malezja",
        "MV": "Malediwy", "MN": "Mongolia", "MM": "Mjanma", "NP": "Nepal", "OM": "Oman",
        "PK": "Pakistan", "PH": "Filipiny", "QA": "Katar", "SA": "Arabia Saudyjska", "SG": "Singapur",
        "LK": "Sri Lanka", "SY": "Syria", "TW": "Tajwan", "TJ": "Tadżykistan", "TH": "Tajlandia",
        "TL": "Timor Wschodni", "AE": "ZEA", "UZ": "Uzbekistan", "VN": "Wietnam", "YE": "Jemen",
        "KP": "Korea Północna", "PS": "Palestyna", "TM": "Turkmenistan", "KR": "Korea Południowa",
        "DZ": "Algeria", "AO": "Angola", "BJ": "Benin", "BW": "Botswana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Kamerun", "CV": "Wyspy Zielonego Przylądka", "CF": "Rep. Środkowoafrykanska",
        "TD": "Czad", "KM": "Komory", "CG": "Kongo", "CD": "Dem. Rep. Konga",
        "CI": "Wybrzeże Kości Słoniowej", "DJ": "Dżibuti", "EG": "Egipt", "GQ": "Gwinea Równikowa", "ER": "Erytrea",
        "ET": "Etiopia", "GA": "Gabon", "GM": "Gambia", "GH": "Ghana", "GN": "Gwinea",
        "GW": "Gwinea Bissau", "KE": "Kenia", "LS": "Lesotho", "LR": "Liberia", "LY": "Libia",
        "MG": "Madagaskar", "MW": "Malawi", "ML": "Mali", "MR": "Mauretania", "MU": "Mauritius",
        "MA": "Maroko", "MZ": "Mozambik", "NA": "Namibia", "NE": "Niger", "NG": "Nigeria",
        "RW": "Rwanda", "ST": "Wyspy Świętego Tomasza i Książęca", "SN": "Senegal", "SC": "Seszele",
        "SL": "Sierra Leone", "SO": "Somalia", "ZA": "Południowa Afryka", "SS": "Sudan Południowy",
        "SD": "Sudan", "SZ": "Eswatini", "TZ": "Tanzania", "TG": "Togo", "TN": "Tunezja",
        "UG": "Uganda", "ZM": "Zambia", "ZW": "Zimbabwe",
        "AR": "Argentyna", "BO": "Boliwia", "BR": "Brazylia", "CL": "Chile", "CO": "Kolumbia",
        "EC": "Ekwador", "GY": "Gujana", "PY": "Paragwaj", "PE": "Peru", "SR": "Surinam",
        "UY": "Urugwaj", "VE": "Wenezuela", "CA": "Kanada", "MX": "Meksyk", "US": "Stany Zjednoczone",
        "AG": "Antigua i Barbuda", "BS": "Bahamy", "BB": "Barbados", "BZ": "Belize",
        "CR": "Kostaryka", "CU": "Kuba", "DM": "Dominika", "DO": "Dominikana",
        "SV": "Salwador", "GD": "Grenada", "GT": "Gwatemala", "HT": "Haiti", "HN": "Honduras",
        "JM": "Jamajka", "NI": "Nikaragua", "PA": "Panama", "KN": "Saint Kitts i Nevis",
        "LC": "Saint Lucia", "VC": "Saint Vincent i Grenadyny", "TT": "Trynidad i Tobago",
        "AU": "Australia", "FJ": "Fidži", "KI": "Kiribati", "MH": "Wyspy Marshalla",
        "FM": "Mikronezja", "NR": "Nauru", "NZ": "Nowa Zelandia", "PW": "Palau", "PG": "Papua-Nowa Gwinea",
        "WS": "Samoa", "SB": "Wyspy Salomona", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let polishCapitals: [String: String] = [
        "AT": "Wiedeń", "AL": "Tirana", "AD": "Andorra la Vella", "AM": "Erewan", "AZ": "Baku",
        "BY": "Mińsk", "BE": "Bruksela", "BA": "Sarajewo", "BG": "Sofia", "HR": "Zagrzeb",
        "CY": "Nikozja", "CZ": "Praga", "DK": "Kopenhaga", "EE": "Tallinn", "FI": "Helsinki",
        "FR": "Paryż", "GE": "Tbilisi", "DE": "Berlin", "GR": "Ateny", "HU": "Budapeszt",
        "IS": "Reykjavík", "IE": "Dublin", "IT": "Rzym", "XK": "Pristina", "LV": "Ryga",
        "LI": "Vaduz", "LT": "Wilno", "LU": "Luksemburg", "MT": "Valletta", "MD": "Kiszyniów",
        "MC": "Monako", "ME": "Podgorica", "NL": "Amsterdam", "MK": "Skopje", "NO": "Oslo",
        "PL": "Warszawa", "PT": "Lizbona", "RO": "Bukareszt", "RU": "Moskwa", "SM": "San Marino",
        "RS": "Belgrad", "SK": "Bratysława", "SI": "Lublana", "ES": "Madryt", "SE": "Sztokholm",
        "CH": "Berno", "TR": "Ankara", "UA": "Kijów", "GB": "Londyn", "VA": "Watykan",
        "AF": "Kabul", "BH": "Manama", "BD": "Dhaka", "BT": "Thimphu", "BN": "Bandar Seri Begawan",
        "KH": "Phnom Penh", "CN": "Pekin", "IN": "Nowe Delhi", "ID": "Dżakarta", "IR": "Teheran",
        "IQ": "Bagdad", "IL": "Jerozolima", "JP": "Tokio", "JO": "Amman", "KZ": "Astana",
        "KW": "Kuwejt", "KG": "Biszken", "LA": "Wientian", "LB": "Bejrut", "MY": "Kuala Lumpur",
        "MV": "Malé", "MN": "Ułan Bator", "MM": "Naypyidaw", "NP": "Katmandu", "OM": "Maskat",
        "PK": "Islamabad", "PH": "Manila", "QA": "Doha", "SA": "Rijad", "SG": "Singapur",
        "LK": "Kolombo", "SY": "Damaszek", "TW": "Tajpej", "TJ": "Duszanbe", "TH": "Bangkok",
        "TL": "Dili", "AE": "Abu Zabi", "UZ": "Taszkent", "VN": "Hanoi", "YE": "Sana",
        "KP": "Pjongjang", "PS": "Ramallah", "TM": "Aszchabad", "KR": "Seul",
        "DZ": "Algier", "AO": "Luanda", "BJ": "Porto-Novo", "BW": "Gaborone", "BF": "Wagadugu",
        "BI": "Gitega", "CM": "Jaunde", "CV": "Praia", "CF": "Bangi", "TD": "Ndżamena",
        "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinszasa", "CI": "Yamoussoukro", "DJ": "Dżibuti",
        "EG": "Kair", "GQ": "Malabo", "ER": "Asmara", "ET": "Addis Abeba", "GA": "Libreville",
        "GM": "Bandżul", "GH": "Akra", "GN": "Konakry", "GW": "Bissau", "KE": "Nairobi",
        "LS": "Maseru", "LR": "Monrovia", "LY": "Trypolis", "MG": "Antananarywa", "MW": "Lilongwe",
        "ML": "Bamako", "MR": "Nouakchott", "MU": "Port Louis", "MA": "Rabat", "MZ": "Maputo",
        "NA": "Windhoek", "NE": "Niamey", "NG": "Abudża", "RW": "Kigali", "ST": "São Tomé",
        "SN": "Dakar", "SC": "Victoria", "SL": "Freetown", "SO": "Mogadiszu", "ZA": "Pretoria",
        "SS": "Dżuba", "SD": "Chartum", "SZ": "Mbabane", "TZ": "Dodoma", "TG": "Lomé",
        "TN": "Tunis", "UG": "Kampala", "ZM": "Lusaka", "ZW": "Harare",
        "AR": "Buenos Aires", "BO": "Sucre", "BR": "Brasília", "CL": "Santiago", "CO": "Bogota",
        "EC": "Quito", "GY": "Georgetown", "PY": "Asunción", "PE": "Lima", "SR": "Paramaribo",
        "UY": "Montevideo", "VE": "Caracas", "CA": "Ottawa", "MX": "Meksyk", "US": "Waszyngton",
        "AG": "Saint John's", "BS": "Nassau", "BB": "Bridgetown", "BZ": "Belmopan", "CR": "San José",
        "CU": "Hawana", "DM": "Roseau", "DO": "Santo Domingo", "SV": "San Salvador", "GD": "Saint George's",
        "GT": "Gwatemala", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "JM": "Kingston",
        "NI": "Managua", "PA": "Panama", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown", "TT": "Port of Spain",
        "AU": "Canberra", "FJ": "Suva", "KI": "Tarawa Południowa", "MH": "Majuro", "FM": "Palikir",
        "NR": "Yaren", "NZ": "Wellington", "PW": "Ngerulmud", "PG": "Port Moresby", "WS": "Apia",
        "SB": "Honiara", "TO": "Nukuʻalofa", "TV": "Funafuti", "VU": "Port Vila"
    ]
    
    // MARK: - Dutch (nl)
    static let dutchNames: [String: String] = [
        "AT": "Oostenrijk", "AL": "Albanië", "AD": "Andorra", "AM": "Armenië", "AZ": "Azerbeidzjan",
        "BY": "Wit-Rusland", "BE": "België", "BA": "Bosnië en Herzegovina", "BG": "Bulgarije",
        "HR": "Kroatië", "CY": "Cyprus", "CZ": "Tsjechië", "DK": "Denemarken", "EE": "Estland",
        "FI": "Finland", "FR": "Frankrijk", "GE": "Georgië", "DE": "Duitsland", "GR": "Griekenland",
        "HU": "Hongarije", "IS": "IJsland", "IE": "Ierland", "IT": "Italië", "XK": "Kosovo",
        "LV": "Letland", "LI": "Liechtenstein", "LT": "Litouwen", "LU": "Luxemburg",
        "MT": "Malta", "MD": "Moldavië", "MC": "Monaco", "ME": "Montenegro", "NL": "Nederland",
        "MK": "Noord-Macedonië", "NO": "Noorwegen", "PL": "Polen", "PT": "Portugal", "RO": "Roemenië",
        "RU": "Rusland", "SM": "San Marino", "RS": "Servië", "SK": "Slowakije", "SI": "Slovenië",
        "ES": "Spanje", "SE": "Zweden", "CH": "Zwitserland", "TR": "Turkije", "UA": "Oekraïne",
        "GB": "Verenigd Koninkrijk", "VA": "Vaticaanstad",
        "AF": "Afghanistan", "BH": "Bahrein", "BD": "Bangladesh", "BT": "Bhutan", "BN": "Brunei",
        "KH": "Cambodja", "CN": "China", "IN": "India", "ID": "Indonesië", "IR": "Iran",
        "IQ": "Irak", "IL": "Israël", "JP": "Japan", "JO": "Jordanië", "KZ": "Kazachstan",
        "KW": "Koeweit", "KG": "Kirgizië", "LA": "Laos", "LB": "Libanon", "MY": "Maleisië",
        "MV": "Maldiven", "MN": "Mongolië", "MM": "Myanmar", "NP": "Nepal", "OM": "Oman",
        "PK": "Pakistan", "PH": "Filipijnen", "QA": "Qatar", "SA": "Saoedi-Arabië", "SG": "Singapore",
        "LK": "Sri Lanka", "SY": "Syrië", "TW": "Taiwan", "TJ": "Tadzjikistan", "TH": "Thailand",
        "TL": "Oost-Timor", "AE": "VAE", "UZ": "Oezbekistan", "VN": "Vietnam", "YE": "Jemen",
        "KP": "Noord-Korea", "PS": "Palestina", "TM": "Turkmenistan", "KR": "Zuid-Korea",
        "DZ": "Algerije", "AO": "Angola", "BJ": "Benin", "BW": "Botswana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Kameroen", "CV": "Kaapverdië", "CF": "Centraal-Afrikaanse Republiek",
        "TD": "Tsjaad", "KM": "Comoren", "CG": "Congo", "CD": "Congo-Kinshasa",
        "CI": "Ivoorkust", "DJ": "Djibouti", "EG": "Egypte", "GQ": "Equatoriaal-Guinea", "ER": "Eritrea",
        "ET": "Ethiopië", "GA": "Gabon", "GM": "Gambia", "GH": "Ghana", "GN": "Guinee",
        "GW": "Guinee-Bissau", "KE": "Kenia", "LS": "Lesotho", "LR": "Liberia", "LY": "Libië",
        "MG": "Madagaskar", "MW": "Malawi", "ML": "Mali", "MR": "Mauritanië", "MU": "Mauritius",
        "MA": "Marokko", "MZ": "Mozambique", "NA": "Namibië", "NE": "Niger", "NG": "Nigeria",
        "RW": "Rwanda", "ST": "Sao Tomé en Principe", "SN": "Senegal", "SC": "Seychellen",
        "SL": "Sierra Leone", "SO": "Somalië", "ZA": "Zuid-Afrika", "SS": "Zuid-Sudan",
        "SD": "Soedan", "SZ": "Eswatini", "TZ": "Tanzania", "TG": "Togo", "TN": "Tunesië",
        "UG": "Oeganda", "ZM": "Zambia", "ZW": "Zimbabwe",
        "AR": "Argentinië", "BO": "Bolivia", "BR": "Brazilië", "CL": "Chili", "CO": "Colombia",
        "EC": "Ecuador", "GY": "Guyana", "PY": "Paraguay", "PE": "Peru", "SR": "Suriname",
        "UY": "Uruguay", "VE": "Venezuela", "CA": "Canada", "MX": "Mexico", "US": "Verenigde Staten",
        "AG": "Antigua en Barbuda", "BS": "Bahama's", "BB": "Barbados", "BZ": "Belize",
        "CR": "Costa Rica", "CU": "Cuba", "DM": "Dominica", "DO": "Dominicaanse Republiek",
        "SV": "El Salvador", "GD": "Grenada", "GT": "Guatemala", "HT": "Haïti", "HN": "Honduras",
        "JM": "Jamaica", "NI": "Nicaragua", "PA": "Panama", "KN": "Saint Kitts en Nevis",
        "LC": "Saint Lucia", "VC": "Saint Vincent en de Grenadines", "TT": "Trinidad en Tobago",
        "AU": "Australië", "FJ": "Fiji", "KI": "Kiribati", "MH": "Marshalleilanden",
        "FM": "Micronesia", "NR": "Nauru", "NZ": "Nieuw-Zeeland", "PW": "Palau", "PG": "Papoea-Nieuw-Guinea",
        "WS": "Samoa", "SB": "Salomonseilanden", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let dutchCapitals: [String: String] = [
        "AT": "Wenen", "AL": "Tirana", "AD": "Andorra la Vella", "AM": "Jerevan", "AZ": "Bakoe",
        "BY": "Minsk", "BE": "Brussel", "BA": "Sarajevo", "BG": "Sofia", "HR": "Zagreb",
        "CY": "Nicosia", "CZ": "Praag", "DK": "Kopenhagen", "EE": "Tallinn", "FI": "Helsinki",
        "FR": "Parijs", "GE": "Tbilisi", "DE": "Berlijn", "GR": "Athene", "HU": "Boedapest",
        "IS": "Reykjavik", "IE": "Dublin", "IT": "Rome", "XK": "Pristina", "LV": "Riga",
        "LI": "Vaduz", "LT": "Vilnius", "LU": "Luxemburg", "MT": "Valletta", "MD": "Chisinau",
        "MC": "Monaco", "ME": "Podgorica", "NL": "Amsterdam", "MK": "Skopje", "NO": "Oslo",
        "PL": "Warschau", "PT": "Lissabon", "RO": "Boekarest", "RU": "Moskou", "SM": "San Marino",
        "RS": "Belgrado", "SK": "Bratislava", "SI": "Ljubljana", "ES": "Madrid", "SE": "Stockholm",
        "CH": "Bern", "TR": "Ankara", "UA": "Kiev", "GB": "Londen", "VA": "Vaticaanstad",
        "AF": "Kabul", "BH": "Manama", "BD": "Dhaka", "BT": "Thimphu", "BN": "Bandar Seri Begawan",
        "KH": "Phnom Penh", "CN": "Peking", "IN": "New Delhi", "ID": "Jakarta", "IR": "Teheran",
        "IQ": "Bagdad", "IL": "Jeruzalem", "JP": "Tokio", "JO": "Amman", "KZ": "Astana",
        "KW": "Koeweit", "KG": "Bisjkek", "LA": "Vientiane", "LB": "Beiroet", "MY": "Kuala Lumpur",
        "MV": "Malé", "MN": "Ulaanbaatar", "MM": "Naypyidaw", "NP": "Kathmandu", "OM": "Muscat",
        "PK": "Islamabad", "PH": "Manilla", "QA": "Doha", "SA": "Riyad", "SG": "Singapore",
        "LK": "Colombo", "SY": "Damascus", "TW": "Taipei", "TJ": "Doesjanbe", "TH": "Bangkok",
        "TL": "Dili", "AE": "Abu Dhabi", "UZ": "Tasjkent", "VN": "Hanoi", "YE": "Sanaa",
        "KP": "Pyongyang", "PS": "Ramallah", "TM": "Asjchabad", "KR": "Seoel",
        "DZ": "Algiers", "AO": "Luanda", "BJ": "Porto-Novo", "BW": "Gaborone", "BF": "Ouagadougou",
        "BI": "Gitega", "CM": "Yaoundé", "CV": "Praia", "CF": "Bangui", "TD": "N'Djamena",
        "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "CI": "Yamoussoukro", "DJ": "Djibouti",
        "EG": "Caïro", "GQ": "Malabo", "ER": "Asmara", "ET": "Addis Abeba", "GA": "Libreville",
        "GM": "Banjul", "GH": "Accra", "GN": "Conakry", "GW": "Bissau", "KE": "Nairobi",
        "LS": "Maseru", "LR": "Monrovia", "LY": "Tripoli", "MG": "Antananarivo", "MW": "Lilongwe",
        "ML": "Bamako", "MR": "Nouakchott", "MU": "Port Louis", "MA": "Rabat", "MZ": "Maputo",
        "NA": "Windhoek", "NE": "Niamey", "NG": "Abuja", "RW": "Kigali", "ST": "São Tomé",
        "SN": "Dakar", "SC": "Victoria", "SL": "Freetown", "SO": "Mogadishu", "ZA": "Pretoria",
        "SS": "Juba", "SD": "Khartoem", "SZ": "Mbabane", "TZ": "Dodoma", "TG": "Lomé",
        "TN": "Tunis", "UG": "Kampala", "ZM": "Lusaka", "ZW": "Harare",
        "AR": "Buenos Aires", "BO": "Sucre", "BR": "Brasília", "CL": "Santiago", "CO": "Bogota",
        "EC": "Quito", "GY": "Georgetown", "PY": "Asunción", "PE": "Lima", "SR": "Paramaribo",
        "UY": "Montevideo", "VE": "Caracas", "CA": "Ottawa", "MX": "Mexico-Stad", "US": "Washington D.C.",
        "AG": "Saint John's", "BS": "Nassau", "BB": "Bridgetown", "BZ": "Belmopan", "CR": "San José",
        "CU": "Havana", "DM": "Roseau", "DO": "Santo Domingo", "SV": "San Salvador", "GD": "Saint George's",
        "GT": "Guatemala-Stad", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "JM": "Kingston",
        "NI": "Managua", "PA": "Panama-Stad", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown", "TT": "Port of Spain",
        "AU": "Canberra", "FJ": "Suva", "KI": "Zuid-Tarawa", "MH": "Majuro", "FM": "Palikir",
        "NR": "Yaren", "NZ": "Wellington", "PW": "Ngerulmud", "PG": "Port Moresby", "WS": "Apia",
        "SB": "Honiara", "TO": "Nukuʻalofa", "TV": "Funafuti", "VU": "Port Vila"
    ]
    
    // MARK: - Portuguese (pt)
    static let portugueseNames: [String: String] = [
        "AT": "Áustria", "AL": "Albânia", "AD": "Andorra", "AM": "Arménia", "AZ": "Azerbaijão",
        "BY": "Bielorrússia", "BE": "Bélgica", "BA": "Bósnia e Herzegovina", "BG": "Bulgária",
        "HR": "Croácia", "CY": "Chipre", "CZ": "Chéquia", "DK": "Dinamarca", "EE": "Estónia",
        "FI": "Finlândia", "FR": "França", "GE": "Geórgia", "DE": "Alemanha", "GR": "Grécia",
        "HU": "Hungria", "IS": "Islândia", "IE": "Irlanda", "IT": "Itália", "XK": "Kosovo",
        "LV": "Letónia", "LI": "Liechtenstein", "LT": "Lituânia", "LU": "Luxemburgo",
        "MT": "Malta", "MD": "Moldávia", "MC": "Mónaco", "ME": "Montenegro", "NL": "Países Baixos",
        "MK": "Macedónia do Norte", "NO": "Noruega", "PL": "Polónia", "PT": "Portugal", "RO": "Roménia",
        "RU": "Rússia", "SM": "San Marino", "RS": "Sérvia", "SK": "Eslováquia", "SI": "Eslovénia",
        "ES": "Espanha", "SE": "Suécia", "CH": "Suíça", "TR": "Turquia", "UA": "Ucrânia",
        "GB": "Reino Unido", "VA": "Vaticano",
        "AF": "Afeganistão", "BH": "Barém", "BD": "Bangladeche", "BT": "Butão", "BN": "Brunei",
        "KH": "Camboja", "CN": "China", "IN": "Índia", "ID": "Indonésia", "IR": "Irão",
        "IQ": "Iraque", "IL": "Israel", "JP": "Japão", "JO": "Jordânia", "KZ": "Cazaquistão",
        "KW": "Kuwait", "KG": "Quirguistão", "LA": "Laos", "LB": "Líbano", "MY": "Malásia",
        "MV": "Maldivas", "MN": "Mongólia", "MM": "Mianmar", "NP": "Nepal", "OM": "Omã",
        "PK": "Paquistão", "PH": "Filipinas", "QA": "Catar", "SA": "Arábia Saudita", "SG": "Singapura",
        "LK": "Sri Lanca", "SY": "Síria", "TW": "Taiwan", "TJ": "Tajiquistão", "TH": "Tailândia",
        "TL": "Timor-Leste", "AE": "Emirados Árabes Unidos", "UZ": "Uzbequistão", "VN": "Vietname", "YE": "Iémen",
        "KP": "Coreia do Norte", "PS": "Palestina", "TM": "Turquemenistão", "KR": "Coreia do Sul",
        "DZ": "Argélia", "AO": "Angola", "BJ": "Benim", "BW": "Botsuana", "BF": "Burkina Faso",
        "BI": "Burundi", "CM": "Camarões", "CV": "Cabo Verde", "CF": "Rep. Centro-Africana",
        "TD": "Chade", "KM": "Comores", "CG": "Congo", "CD": "Rep. Dem. do Congo",
        "CI": "Costa do Marfim", "DJ": "Jibuti", "EG": "Egito", "GQ": "Guiné Equatorial", "ER": "Eritreia",
        "ET": "Etiópia", "GA": "Gabão", "GM": "Gâmbia", "GH": "Gana", "GN": "Guiné",
        "GW": "Guiné-Bissau", "KE": "Quénia", "LS": "Lesoto", "LR": "Libéria", "LY": "Líbia",
        "MG": "Madagáscar", "MW": "Maláui", "ML": "Mali", "MR": "Mauritânia", "MU": "Maurícia",
        "MA": "Marrocos", "MZ": "Moçambique", "NA": "Namíbia", "NE": "Níger", "NG": "Nigéria",
        "RW": "Ruanda", "ST": "São Tomé e Príncipe", "SN": "Senegal", "SC": "Seicheles",
        "SL": "Serra Leoa", "SO": "Somália", "ZA": "África do Sul", "SS": "Sudão do Sul",
        "SD": "Sudão", "SZ": "Essuatíni", "TZ": "Tanzânia", "TG": "Togo", "TN": "Tunísia",
        "UG": "Uganda", "ZM": "Zâmbia", "ZW": "Zimbabué",
        "AR": "Argentina", "BO": "Bolívia", "BR": "Brasil", "CL": "Chile", "CO": "Colômbia",
        "EC": "Equador", "GY": "Guiana", "PY": "Paraguai", "PE": "Peru", "SR": "Suriname",
        "UY": "Uruguai", "VE": "Venezuela", "CA": "Canadá", "MX": "México", "US": "Estados Unidos",
        "AG": "Antígua e Barbuda", "BS": "Bahamas", "BB": "Barbados", "BZ": "Belize",
        "CR": "Costa Rica", "CU": "Cuba", "DM": "Dominica", "DO": "República Dominicana",
        "SV": "Salvador", "GD": "Granada", "GT": "Guatemala", "HT": "Haiti", "HN": "Honduras",
        "JM": "Jamaica", "NI": "Nicarágua", "PA": "Panamá", "KN": "São Cristóvão e Nevis",
        "LC": "Santa Lúcia", "VC": "São Vicente e Granadinas", "TT": "Trindade e Tobago",
        "AU": "Austrália", "FJ": "Fiji", "KI": "Quiribáti", "MH": "Ilhas Marshall",
        "FM": "Micronésia", "NR": "Nauru", "NZ": "Nova Zelândia", "PW": "Palau", "PG": "Papua-Nova Guiné",
        "WS": "Samoa", "SB": "Ilhas Salomão", "TO": "Tonga", "TV": "Tuvalu", "VU": "Vanuatu"
    ]
    static let portugueseCapitals: [String: String] = [
        "AT": "Viena", "AL": "Tirana", "AD": "Andorra-a-Velha", "AM": "Erevan", "AZ": "Bacu",
        "BY": "Minsk", "BE": "Bruxelas", "BA": "Sarajevo", "BG": "Sófia", "HR": "Zagrebe",
        "CY": "Nicósia", "CZ": "Praga", "DK": "Copenhaga", "EE": "Talim", "FI": "Helsínquia",
        "FR": "Paris", "GE": "Tbilisi", "DE": "Berlim", "GR": "Atenas", "HU": "Budapeste",
        "IS": "Reiquiavique", "IE": "Dublino", "IT": "Roma", "XK": "Pristina", "LV": "Riga",
        "LI": "Vaduz", "LT": "Vilnius", "LU": "Luxemburgo", "MT": "Valeta", "MD": "Quichinau",
        "MC": "Mónaco", "ME": "Podgorica", "NL": "Amesterdão", "MK": "Escópia", "NO": "Oslo",
        "PL": "Varsóvia", "PT": "Lisboa", "RO": "Bucareste", "RU": "Moscovo", "SM": "San Marino",
        "RS": "Belgrado", "SK": "Bratislava", "SI": "Liubliana", "ES": "Madrid", "SE": "Estocolmo",
        "CH": "Berna", "TR": "Ancara", "UA": "Kiev", "GB": "Londres", "VA": "Vaticano",
        "AF": "Cabul", "BH": "Manama", "BD": "Daca", "BT": "Thimphu", "BN": "Bandar Seri Begawan",
        "KH": "Phnom Penh", "CN": "Pequim", "IN": "Nova Deli", "ID": "Jacarta", "IR": "Teerão",
        "IQ": "Bagdade", "IL": "Jerusalém", "JP": "Tóquio", "JO": "Amã", "KZ": "Astana",
        "KW": "Kuwait", "KG": "Bisqueque", "LA": "Vientiane", "LB": "Beirute", "MY": "Kuala Lumpur",
        "MV": "Malé", "MN": "Ulan Bator", "MM": "Naypyidaw", "NP": "Catmandu", "OM": "Mascate",
        "PK": "Islamabade", "PH": "Manila", "QA": "Doha", "SA": "Riade", "SG": "Singapura",
        "LK": "Colombo", "SY": "Damasco", "TW": "Taipé", "TJ": "Duchambé", "TH": "Bangkok",
        "TL": "Díli", "AE": "Abu Dhabi", "UZ": "Tashkent", "VN": "Hanói", "YE": "Saná",
        "KP": "Pyongyang", "PS": "Ramala", "TM": "Asgabate", "KR": "Seul",
        "DZ": "Argel", "AO": "Luanda", "BJ": "Porto-Novo", "BW": "Gaborone", "BF": "Uagadugu",
        "BI": "Gitega", "CM": "Yaoundé", "CV": "Praia", "CF": "Bangui", "TD": "N'Djamena",
        "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "CI": "Yamoussoukro", "DJ": "Jibuti",
        "EG": "Cairo", "GQ": "Malabo", "ER": "Asmara", "ET": "Adis Abeba", "GA": "Libreville",
        "GM": "Banjul", "GH": "Acra", "GN": "Conacri", "GW": "Bissau", "KE": "Nairóbi",
        "LS": "Maseru", "LR": "Monróvia", "LY": "Trípoli", "MG": "Antananarivo", "MW": "Lilongwe",
        "ML": "Bamaco", "MR": "Nouakchott", "MU": "Port Louis", "MA": "Rabat", "MZ": "Maputo",
        "NA": "Windhoek", "NE": "Niamey", "NG": "Abuja", "RW": "Kigali", "ST": "São Tomé",
        "SN": "Dacar", "SC": "Vitória", "SL": "Freetown", "SO": "Mogadíscio", "ZA": "Pretória",
        "SS": "Juba", "SD": "Cartum", "SZ": "Mbabane", "TZ": "Dodoma", "TG": "Lomé",
        "TN": "Tunes", "UG": "Campala", "ZM": "Lusaka", "ZW": "Harare",
        "AR": "Buenos Aires", "BO": "Sucre", "BR": "Brasília", "CL": "Santiago", "CO": "Bogotá",
        "EC": "Quito", "GY": "Georgetown", "PY": "Assunção", "PE": "Lima", "SR": "Paramaribo",
        "UY": "Montevideu", "VE": "Caracas", "CA": "Ottawa", "MX": "Cidade do México", "US": "Washington D.C.",
        "AG": "Saint John's", "BS": "Nassau", "BB": "Bridgetown", "BZ": "Belmopã", "CR": "São José",
        "CU": "Havana", "DM": "Roseau", "DO": "Santo Domingo", "SV": "San Salvador", "GD": "Saint George's",
        "GT": "Cidade da Guatemala", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "JM": "Kingston",
        "NI": "Manágua", "PA": "Cidade do Panamá", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown", "TT": "Port of Spain",
        "AU": "Canberra", "FJ": "Suva", "KI": "Tarawa do Sul", "MH": "Majuro", "FM": "Paliquir",
        "NR": "Yaren", "NZ": "Wellington", "PW": "Ngerulmud", "PG": "Port Moresby", "WS": "Apia",
        "SB": "Honiara", "TO": "Nukuʻalofa", "TV": "Funafuti", "VU": "Port Vila"
    ]
}
