# -*- coding: utf-8 -*-
"""Данные для survival_tc_overlay.json — pivot по ключу локализации."""
from __future__ import annotations

ALL_LANGS = (
    "ar",
    "bn",
    "ca",
    "cs",
    "de",
    "el",
    "es",
    "fil",
    "fr",
    "hi",
    "hu",
    "id",
    "it",
    "ja",
    "ko",
    "nl",
    "pl",
    "pt-BR",
    "ro",
    "ru",
    "sv",
    "ta",
    "te",
    "th",
    "tr",
    "uk",
    "vi",
    "zh",
    "zh-Hant",
)

# Каждый ключ — полный набор переводов (29 языков)
T: dict[str, dict[str, str]] = {
    "Answer as many flags as possible before time runs out": {
        "de": "Beantworte so viele Flaggen wie möglich, bevor die Zeit abläuft",
        "fr": "Répondez à autant de drapeaux que possible avant la fin du temps",
        "es": "Responde a tantas banderas como puedas antes de que se acabe el tiempo",
        "it": "Indovina più bandiere possibile prima che finisca il tempo",
        "pt-BR": "Acerte o máximo de bandeiras possível antes do tempo acabar",
        "pl": "Odpowiedz na jak najwięcej flag, zanim skończy się czas",
        "nl": "Beantwoord zoveel mogelijk vlaggen voordat de tijd om is",
        "ca": "Encerta tantes banderes com puguis abans que s’acabi el temps",
        "sv": "Svara på så många flaggor du kan innan tiden tar slut",
        "cs": "Odpověz na co nejvíce vlajek, než vyprší čas",
        "ro": "Răspunde la cât mai multe steaguri înainte să se termine timpul",
        "hu": "Válaszolj annyi zászlóra, amennyire csak tudsz, mielőtt lejár az idő",
        "el": "Απάντησε σε όσες περισσότερες σημαίες μπορείς πριν τελειώσει ο χρόνος",
        "tr": "Süre dolmadan olabildiğince çok bayrak bil",
        "uk": "Відповідай на якнайбільше прапорів, доки не скінчиться час",
        "vi": "Trả lời càng nhiều lá cờ càng tốt trước khi hết giờ",
        "th": "ตอบธงให้ได้มากที่สุดก่อนหมดเวลา",
        "id": "Jawab sebanyak mungkin bendera sebelum waktu habis",
        "fil": "Sagutin ang maraming watawat hangga’t maaari bago maubos ang oras",
        "hi": "समय खत्म होने से पहले जितनी हो सके उतनी झंडियाँ पहचानें",
        "bn": "সময় শেষ হওয়ার আগে যত বেশি সম্ভব পতাকা উত্তর দিন",
        "ta": "நேரம் முடிவதற்குள் முடிந்த அளவு கொடிகளுக்கு பதிலளிக்கவும்",
        "te": "సమయం అయిపోకముందు ఎక్కువ జండాలకు సమాధానం ఇవ్వండి",
        "ar": "أجب عن أكبر عدد ممكن من الأعلام قبل انتهاء الوقت",
        "ja": "時間が切れる前に、できるだけ多くの国旗に答えよう",
        "ko": "시간이 끝나기 전에 최대한 많은 국기를 맞히세요",
        "zh": "在时间结束前尽可能多地答对国旗",
        "zh-Hant": "在時間結束前盡可能答對更多國旗",
        "ru": "Угадайте как можно больше флагов, пока не истечёт время",
    },
    "Duration": {
        "de": "Dauer",
        "fr": "Durée",
        "es": "Duración",
        "it": "Durata",
        "pt-BR": "Duração",
        "pl": "Czas trwania",
        "nl": "Duur",
        "ca": "Durada",
        "sv": "Längd",
        "cs": "Délka",
        "ro": "Durată",
        "hu": "Időtartam",
        "el": "Διάρκεια",
        "tr": "Süre",
        "uk": "Тривалість",
        "vi": "Thời lượng",
        "th": "ระยะเวลา",
        "id": "Durasi",
        "fil": "Tagal",
        "hi": "अवधि",
        "bn": "সময়কাল",
        "ta": "கால அளவு",
        "te": "కాలం",
        "ar": "المدة",
        "ja": "制限時間",
        "ko": "제한 시간",
        "zh": "时长",
        "zh-Hant": "時長",
        "ru": "Длительность",
    },
    "Wrong answer penalty": {
        "de": "Strafe bei falscher Antwort",
        "fr": "Pénalité pour mauvaise réponse",
        "es": "Penalización por error",
        "it": "Penalità risposta sbagliata",
        "pt-BR": "Penalidade por erro",
        "pl": "Kara za błędną odpowiedź",
        "nl": "Straf bij fout antwoord",
        "ca": "Penalització per resposta incorrecta",
        "sv": "Straff vid fel svar",
        "cs": "Trest za špatnou odpověď",
        "ro": "Penalizare răspuns greșit",
        "hu": "Büntetés rossz válaszért",
        "el": "Ποινή λάθους απάντησης",
        "tr": "Yanlış cevap cezası",
        "uk": "Штраф за помилку",
        "vi": "Phạt khi trả lời sai",
        "th": "โทษเมื่อตอบผิด",
        "id": "Penalti jawaban salah",
        "fil": "Parusa sa maling sagot",
        "hi": "गलत जवाब पर जुर्माना",
        "bn": "ভুল উত্তরের শাস্তি",
        "ta": "தவறான பதிலுக்கு தண்டனை",
        "te": "తప్పు సమాధానానికి జరిమానా",
        "ar": "عقوبة الإجابة الخاطئة",
        "ja": "不正解のペナルティ",
        "ko": "오답 페널티",
        "zh": "答错惩罚",
        "zh-Hant": "答錯懲罰",
        "ru": "Штраф за ошибку",
    },
    "5 correct in a row bonus": {
        "de": "Bonus für 5 richtige in Folge",
        "fr": "Bonus pour 5 bonnes réponses d’affilée",
        "es": "Bonus por 5 aciertos seguidos",
        "it": "Bonus 5 corrette di fila",
        "pt-BR": "Bônus por 5 acertos seguidos",
        "pl": "Bonus za 5 poprawnych z rzędu",
        "nl": "Bonus bij 5 goed op rij",
        "ca": "Bonus per 5 encerts seguits",
        "sv": "Bonus för 5 rätt i rad",
        "cs": "Bonus za 5 správných v řadě",
        "ro": "Bonus pentru 5 corecte la rând",
        "hu": "Bónusz 5 egymás utáni helyesre",
        "el": "Μπόνους για 5 σωστές στη σειρά",
        "tr": "Üst üste 5 doğru bonusu",
        "uk": "Бонус за 5 вірних поспіль",
        "vi": "Thưởng cho 5 câu đúng liên tiếp",
        "th": "โบนัส 5 ข้อถูกติดกัน",
        "id": "Bonus 5 benar beruntun",
        "fil": "Bonus sa 5 tamang sunod-sunod",
        "hi": "लगातार 5 सही पर बोनस",
        "bn": "টানা ৫টি সঠিক বোনাস",
        "ta": "தொடர்ந்து 5 சரிக்கு போனஸ்",
        "te": "వరుసగా 5 సరైనవికి బోనస్",
        "ar": "مكافأة لـ 5 إجابات صحيحة متتالية",
        "ja": "連続5正解ボーナス",
        "ko": "연속 5정답 보너스",
        "zh": "连续答对 5 题奖励",
        "zh-Hant": "連續答對 5 題獎勵",
        "ru": "Бонус за 5 верных подряд",
    },
    "Best combo": {
        "de": "Beste Serie",
        "fr": "Meilleur combo",
        "es": "Mejor racha",
        "it": "Miglior serie",
        "pt-BR": "Melhor sequência",
        "pl": "Najlepsza seria",
        "nl": "Beste reeks",
        "ca": "Millor ratxa",
        "sv": "Bästa serie",
        "cs": "Nejlepší série",
        "ro": "Cel mai bun șir",
        "hu": "Legjobb sorozat",
        "el": "Καλύτερο σερί",
        "tr": "En iyi seri",
        "uk": "Найкраща серія",
        "vi": "Chuỗi tốt nhất",
        "th": "คอมโบที่ดีที่สุด",
        "id": "Kombo terbaik",
        "fil": "Pinakamahusay na combo",
        "hi": "सबसे अच्छी लकीर",
        "bn": "সেরা কম্বো",
        "ta": "சிறந்த தொடர்",
        "te": "ఉత్తమ కాంబో",
        "ar": "أفضل سلسلة",
        "ja": "最高コンボ",
        "ko": "최고 콤보",
        "zh": "最佳连击",
        "zh-Hant": "最佳連擊",
        "ru": "Лучшая серия",
    },
    "TC stat best combo": {
        "de": "Beste Serie",
        "fr": "Meilleur combo",
        "es": "Mejor racha",
        "it": "Miglior serie",
        "pt-BR": "Melhor sequência",
        "pl": "Najlepsza seria",
        "nl": "Beste reeks",
        "ca": "Millor ratxa",
        "sv": "Bästa serie",
        "cs": "Nejlepší série",
        "ro": "Cel mai bun șir",
        "hu": "Legjobb sorozat",
        "el": "Καλύτερο σερί",
        "tr": "En iyi seri",
        "uk": "Найкраща серія",
        "vi": "Chuỗi tốt nhất",
        "th": "คอมโบที่ดีที่สุด",
        "id": "Kombo terbaik",
        "fil": "Pinakamahusay na combo",
        "hi": "सबसे अच्छी लकीर",
        "bn": "সেরা কম্বো",
        "ta": "சிறந்த தொடர்",
        "te": "ఉత్తమ కాంబో",
        "ar": "أفضل سلسلة",
        "ja": "最高コンボ",
        "ko": "최고 콤보",
        "zh": "最佳连击",
        "zh-Hant": "最佳連擊",
        "ru": "Лучшая серия",
    },
    "Start": {
        "de": "Start",
        "fr": "Commencer",
        "es": "Empezar",
        "it": "Inizia",
        "pt-BR": "Começar",
        "pl": "Start",
        "nl": "Start",
        "ca": "Començar",
        "sv": "Starta",
        "cs": "Start",
        "ro": "Start",
        "hu": "Indítás",
        "el": "Έναρξη",
        "tr": "Başla",
        "uk": "Старт",
        "vi": "Bắt đầu",
        "th": "เริ่ม",
        "id": "Mulai",
        "fil": "Simula",
        "hi": "शुरू करें",
        "bn": "শুরু",
        "ta": "தொடங்கு",
        "te": "ప్రారంభం",
        "ar": "ابدأ",
        "ja": "スタート",
        "ko": "시작",
        "zh": "开始",
        "zh-Hant": "開始",
        "ru": "Старт",
    },
    "New record!": {
        "de": "Neuer Rekord!",
        "fr": "Nouveau record !",
        "es": "¡Nuevo récord!",
        "it": "Nuovo record!",
        "pt-BR": "Novo recorde!",
        "pl": "Nowy rekord!",
        "nl": "Nieuw record!",
        "ca": "Rècord nou!",
        "sv": "Nytt rekord!",
        "cs": "Nový rekord!",
        "ro": "Record nou!",
        "hu": "Új rekord!",
        "el": "Νέο ρεκόρ!",
        "tr": "Yeni rekor!",
        "uk": "Новий рекорд!",
        "vi": "Kỷ lục mới!",
        "th": "สถิติใหม่!",
        "id": "Rekor baru!",
        "fil": "Bagong record!",
        "hi": "नया रिकॉर्ड!",
        "bn": "নতুন রেকর্ড!",
        "ta": "புதிய சாதனை!",
        "te": "కొత్త రికార్డ్!",
        "ar": "رقم قياسي جديد!",
        "ja": "新記録！",
        "ko": "신기록!",
        "zh": "新纪录！",
        "zh-Hant": "新紀錄！",
        "ru": "Новый рекорд!",
    },
    "Day leaderboard place": {
        "de": "Platz im Tages-Ranking",
        "fr": "Place au classement du jour",
        "es": "Puesto en la clasificación diaria",
        "it": "Posizione classifica giornaliera",
        "pt-BR": "Posição no ranking do dia",
        "pl": "Miejsce w rankingu dziennym",
        "nl": "Plek op dagelijkse ranglijst",
        "ca": "Lloc al rànquing diari",
        "sv": "Placering dagens topplista",
        "cs": "Místo v denním žebříčku",
        "ro": "Loc în clasamentul zilei",
        "hu": "Hely a napi ranglistán",
        "el": "Θέση στην ημερήσια κατάταξη",
        "tr": "Günlük sıralamadaki yer",
        "uk": "Місце в денному рейтингу",
        "vi": "Thứ hạng bảng xếp hạng ngày",
        "th": "อันดับกระดานผู้นำรายวัน",
        "id": "Peringkat papan hari ini",
        "fil": "Puwesto sa leaderboard ng araw",
        "hi": "दिन की लीडरबोर्ड रैंक",
        "bn": "দৈনিক লিডারবোর্ডে স্থান",
        "ta": "நாள் தலைமைப் பலகை இடம்",
        "te": "రోజువారీ లీడర్‌బోర్డ్ స్థానం",
        "ar": "المركز في لوحة المتصدرين اليومية",
        "ja": "デイリーランキング順位",
        "ko": "일간 리더보드 순위",
        "zh": "日榜名次",
        "zh-Hant": "日榜名次",
        "ru": "Место в дневном рейтинге",
    },
    "Week leaderboard place": {
        "de": "Platz im Wochen-Ranking",
        "fr": "Place au classement de la semaine",
        "es": "Puesto en la clasificación semanal",
        "it": "Posizione classifica settimanale",
        "pt-BR": "Posição no ranking da semana",
        "pl": "Miejsce w rankingu tygodniowym",
        "nl": "Plek op wekelijkse ranglijst",
        "ca": "Lloc al rànquing setmanal",
        "sv": "Placering veckans topplista",
        "cs": "Místo v týdenním žebříčku",
        "ro": "Loc în clasamentul săptămânii",
        "hu": "Hely a heti ranglistán",
        "el": "Θέση στην εβδομαδιαία κατάταξη",
        "tr": "Haftalık sıralamadaki yer",
        "uk": "Місце в тижневому рейтингу",
        "vi": "Thứ hạng bảng xếp hạng tuần",
        "th": "อันดับกระดานผู้นำรายสัปดาห์",
        "id": "Peringkat papan mingguan",
        "fil": "Puwesto sa leaderboard ng linggo",
        "hi": "साप्ताहिक लीडरबोर्ड रैंक",
        "bn": "সাপ্তাহিক লিডারবোর্ডে স্থান",
        "ta": "வார தலைமைப் பலகை இடம்",
        "te": "వారపు లీడర్‌బోర్డ్ స్థానం",
        "ar": "المركز في لوحة المتصدرين الأسبوعية",
        "ja": "ウィークリーランキング順位",
        "ko": "주간 리더보드 순위",
        "zh": "周榜名次",
        "zh-Hant": "週榜名次",
        "ru": "Место в недельном рейтинге",
    },
    "Share Survival headline": {
        "de": "Survival: %d Flaggen überlebt • %d richtig • max. Stufe %d",
        "fr": "Survie : %d drapeaux survécus • %d bonnes réponses • étape max %d",
        "es": "Supervivencia: sobreviviste %d banderas • %d aciertos • etapa máx. %d",
        "it": "Sopravvivenza: %d bandiere • %d corrette • livello max %d",
        "pt-BR": "Sobrevivência: %d bandeiras • %d acertos • estágio máx. %d",
        "pl": "Survival: przetrwano %d flag • %d poprawnych • max etap %d",
        "nl": "Survival: %d vlaggen overleefd • %d goed • max. niveau %d",
        "ca": "Supervivència: %d banderes • %d encerts • etapa màx. %d",
        "sv": "Survival: %d flaggor överlevda • %d rätt • max nivå %d",
        "cs": "Survival: přežito %d vlajek • %d správně • max. fáze %d",
        "ro": "Supraviețuire: %d steaguri • %d corecte • nivel max %d",
        "hu": "Túlélés: %d zászló • %d helyes • max. szint %d",
        "el": "Επιβίωση: %d σημαίες • %d σωστές • μέγ. στάδιο %d",
        "tr": "Hayatta kalma: %d bayrak • %d doğru • max aşama %d",
        "uk": "Виживання: %d прапорів • %d вірних • макс. етап %d",
        "vi": "Sinh tồn: %d lá cờ • %d đúng • giai đoạn tối đa %d",
        "th": "เอาชีวิตรอด: %d ธง • %d ถูก • เวทีสูงสุด %d",
        "id": "Survival: %d bendera • %d benar • tahap maks %d",
        "fil": "Survival: %d watawat • %d tama • max stage %d",
        "hi": "सर्वाइवल: %d झंडे • %d सही • अधिकतम स्तर %d",
        "bn": "সারভাইভাল: %d পতাকা • %d সঠিক • সর্বোচ্চ স্তর %d",
        "ta": "உயிர் பிழைப்பு: %d கொடிகள் • %d சரி • அதிகபட்ச நிலை %d",
        "te": "సర్వైవల్: %d జండాలు • %d సరైనవి • గరిష్ట దశ %d",
        "ar": "البقاء: %d علم • %d صحيحة • أقصى مرحلة %d",
        "ja": "サバイバル: %d 国旗 • 正解 %d • 最高ステージ %d",
        "ko": "서바이벌: %d개 국기 • 정답 %d • 최고 스테이지 %d",
        "zh": "生存模式：存活 %d 面旗 • 答对 %d • 最高阶段 %d",
        "zh-Hant": "生存模式：存活 %d 面旗 • 答對 %d • 最高階段 %d",
        "ru": "Выживание: %d флагов • %d верных • макс. этап %d",
    },
    "Survival mode short description": {
        "de": "Begrenzte Leben, steigende Schwierigkeit — wie weit schaffst du es?",
        "fr": "Vies limitées, difficulté croissante — jusqu’où irez-vous ?",
        "es": "Vidas limitadas, dificultad creciente — ¿hasta dónde llegarás?",
        "it": "Vite limitate, difficoltà crescente — fin dove arrivi?",
        "pt-BR": "Vidas limitadas, dificuldade crescente — até onde você vai?",
        "pl": "Ograniczone życia, rosnący poziom — jak daleko zajdziesz?",
        "nl": "Beperkt levens, oplopende moeilijkheid — hoever kom je?",
        "ca": "Vides limitades, dificultat creixent — fins on arribaràs?",
        "sv": "Begränsade liv, stigande svårighet — hur långt klarar du?",
        "cs": "Omezené životy, rostoucí obtížnost — jak daleko dojdeš?",
        "ro": "Vieți limitate, dificultate în creștere — cât de departe ajungi?",
        "hu": "Korlátozott életek, növekvő nehézség — meddig jutsz?",
        "el": "Περιορισμένες ζωές, αυξανόμενη δυσκολία — πόσο μακριά θα φτάσεις;",
        "tr": "Sınırlı can, artan zorluk — ne kadar ilerlersin?",
        "uk": "Обмежені життя, зростає складність — як далеко зможете?",
        "vi": "Mạng hạn chế, độ khó tăng dần — bạn đi được xa đến đâu?",
        "th": "ชีวิตจำกัด ความยากขึ้นเรื่อย ๆ — คุณจะไปได้ไกลแค่ไหน?",
        "id": "Nyawa terbatas, kesulitan naik — sejauh mana kamu bisa?",
        "fil": "Limitadong buhay, tumataas na hirap — hanggang saan ka aabot?",
        "hi": "सीमित जीवन, बढ़ती कठिनाई — आप कितनी दूर जा सकते हैं?",
        "bn": "সীমিত জীবন, কঠিনতা বাড়ছে — আপনি কতদূর যেতে পারবেন?",
        "ta": "வரையறுக்கப்பட்ட உயிர்கள், அதிகரிக்கும் சிரமம் — எவ்வளவு தூரம் செல்வீர்கள்?",
        "te": "పరిమిత జీవితాలు, పెరిగే కష్టం — మీరు ఎంత దూరం వెళ్తారు?",
        "ar": "حيوات محدودة وصعوبة متزايدة — إلى أين ستصل؟",
        "ja": "ライフは限られ、難易度は上昇 — どこまでいける？",
        "ko": "제한된 생명, 난이도 상승 — 어디까지 갈 수 있을까요?",
        "zh": "生命有限、难度递增——你能走多远？",
        "zh-Hant": "生命有限、難度遞增——你能走多遠？",
        "ru": "Ограниченные жизни и рост сложности — как далеко зайдёте?",
    },
    "Survival difficulty blurb fmt": {
        "de": "Leben pro Durchgang • steigende Stufen • +1 Leben je 10 richtige in Folge",
        "fr": "Vies de session • paliers progressifs • +1 vie tous les 10 bons d’affilée",
        "es": "Vidas de la partida • etapas progresivas • +1 vida cada 10 aciertos seguidos",
        "it": "Vite sessione • stage crescenti • +1 vita ogni 10 corrette di fila",
        "pt-BR": "Vidas da sessão • fases crescentes • +1 vida a cada 10 acertos seguidos",
        "pl": "Życia sesji • rosnące etapy • +1 życie co 10 poprawnych z rzędu",
        "nl": "Levens per sessie • oplopende levels • +1 leven per 10 goed op rij",
        "ca": "Vides de la sessió • etapes creixents • +1 vida cada 10 encerts seguits",
        "sv": "Liv per omgång • stigande nivåer • +1 liv per 10 rätt i rad",
        "cs": "Životy za session • rostoucí fáze • +1 život za 10 správných v řadě",
        "ro": "Vieți sesiune • etape în creștere • +1 viață la fiecare 10 corecte la rând",
        "hu": "Életek menetenként • emelkedő szintek • +1 élet minden 10 helyesre egymás után",
        "el": "Ζωές συνεδρίας • αυξανόμενα στάδια • +1 ζωή ανά 10 σωστές στη σειρά",
        "tr": "Oturum canları • artan aşamalar • üst üste 10 doğruya +1 can",
        "uk": "Життя за сесію • зростання етапів • +1 життя за кожні 10 вірних поспіль",
        "vi": "Mạng mỗi phiên • tăng giai đoạn • +1 mạng mỗi 10 câu đúng liên tiếp",
        "th": "ชีวิตต่อรอบ • เวทีสูงขึ้น • +1 ชีวิตทุก 10 ข้อถูกติดกัน",
        "id": "Nyawa sesi • tahap naik • +1 nyawa tiap 10 benar beruntun",
        "fil": "Buhay bawat session • tumataas na stage • +1 buhay bawat 10 tamang sunod-sunod",
        "hi": "सत्र जीवन • बढ़ते चरण • लगातार 10 सही पर +1 जीवन",
        "bn": "সেশন জীবন • বাড়তি পর্যায় • টানা ১০টি সঠিকে +১ জীবন",
        "ta": "அமர்வு உயிர்கள் • அதிகரிக்கும் நிலைகள் • தொடர்ந்து 10 சரிக்கு +1 உயிர்",
        "te": "సెషన్ జీవితాలు • పెరిగే దశలు • వరుసగా 10 సరైనవికి +1 జీవితం",
        "ar": "حيوات الجلسة • مراحل تصاعدية • +1 حياة كل 10 إجابات صحيحة متتالية",
        "ja": "セッションライフ・段階上昇・連続10正解で+1ライフ",
        "ko": "세션 생명 • 단계 상승 • 연속 10정담마다 +1 생명",
        "zh": "回合生命 · 阶段提升 · 连续答对 10 题 +1 生命",
        "zh-Hant": "回合生命 · 階段提升 · 連續答對 10 題 +1 生命",
        "ru": "Жизни сессии • этапы сложности • +1 жизнь за каждые 10 верных подряд",
    },
    "Survival depth header": {
        "de": "Tiefe",
        "fr": "Profondeur",
        "es": "Profundidad",
        "it": "Profondità",
        "pt-BR": "Profundidade",
        "pl": "Głębokość",
        "nl": "Diepte",
        "ca": "Profunditat",
        "sv": "Djup",
        "cs": "Hloubka",
        "ro": "Adâncime",
        "hu": "Mélység",
        "el": "Βάθος",
        "tr": "Derinlik",
        "uk": "Глибина",
        "vi": "Độ sâu",
        "th": "ความลึก",
        "id": "Kedalaman",
        "fil": "Lalim",
        "hi": "गहराई",
        "bn": "গভীরতা",
        "ta": "ஆழம்",
        "te": "లోతు",
        "ar": "العمق",
        "ja": "深度",
        "ko": "깊이",
        "zh": "深度",
        "zh-Hant": "深度",
        "ru": "Глубина",
    },
    "Survival stage fmt": {
        "de": "Stufe %d",
        "fr": "Étape %d",
        "es": "Etapa %d",
        "it": "Fase %d",
        "pt-BR": "Fase %d",
        "pl": "Etap %d",
        "nl": "Niveau %d",
        "ca": "Etapa %d",
        "sv": "Nivå %d",
        "cs": "Fáze %d",
        "ro": "Nivel %d",
        "hu": "%d. szint",
        "el": "Στάδιο %d",
        "tr": "Aşama %d",
        "uk": "Етап %d",
        "vi": "Giai đoạn %d",
        "th": "เวที %d",
        "id": "Tahap %d",
        "fil": "Stage %d",
        "hi": "स्तर %d",
        "bn": "স্তর %d",
        "ta": "நிலை %d",
        "te": "దశ %d",
        "ar": "المرحلة %d",
        "ja": "ステージ %d",
        "ko": "스테이지 %d",
        "zh": "第 %d 阶段",
        "zh-Hant": "第 %d 階段",
        "ru": "Этап %d",
    },
    "Survival bonus life streak": {
        "de": "+1 Leben (10 richtige in Folge)",
        "fr": "+1 vie (10 bonnes réponses d’affilée)",
        "es": "+1 vida (racha de 10 aciertos)",
        "it": "+1 vita (10 corrette di fila)",
        "pt-BR": "+1 vida (sequência de 10 acertos)",
        "pl": "+1 życie (seria 10 poprawnych)",
        "nl": "+1 leven (10 goed op rij)",
        "ca": "+1 vida (10 encerts seguits)",
        "sv": "+1 liv (10 rätt i rad)",
        "cs": "+1 život (10 správných v řadě)",
        "ro": "+1 viață (10 corecte la rând)",
        "hu": "+1 élet (10 helyes egymás után)",
        "el": "+1 ζωή (10 σωστές στη σειρά)",
        "tr": "+1 can (üst üste 10 doğru)",
        "uk": "+1 життя (10 вірних поспіль)",
        "vi": "+1 mạng (10 câu đúng liên tiếp)",
        "th": "+1 ชีวิต (10 ข้อถูกติดกัน)",
        "id": "+1 nyawa (10 benar beruntun)",
        "fil": "+1 buhay (10 tamang sunod-sunod)",
        "hi": "+1 जीवन (लगातार 10 सही)",
        "bn": "+১ জীবন (টানা ১০টি সঠিক)",
        "ta": "+1 உயிர் (தொடர்ந்து 10 சரி)",
        "te": "+1 జీవితం (వరుసగా 10 సరైనవి)",
        "ar": "+1 حياة (10 إجابات صحيحة متتالية)",
        "ja": "+1ライフ（連続10正解）",
        "ko": "+1 생명 (연속 10정답)",
        "zh": "+1 生命（连续答对 10 题）",
        "zh-Hant": "+1 生命（連續答對 10 題）",
        "ru": "+1 жизнь (серия 10 верных)",
    },
    "Survival milestone banner fmt": {
        "de": "Meilenstein %d! +30 XP • +1 F-Bucks",
        "fr": "Étape %d ! +30 XP • +1 F-Bucks",
        "es": "¡Hito %d! +30 XP • +1 F-Bucks",
        "it": "Traguardo %d! +30 XP • +1 F-Bucks",
        "pt-BR": "Marco %d! +30 XP • +1 F-Bucks",
        "pl": "Kamień milowy %d! +30 XP • +1 F-Bucks",
        "nl": "Mijlpaal %d! +30 XP • +1 F-Bucks",
        "ca": "Fita %d! +30 XP • +1 F-Bucks",
        "sv": "Milstolpe %d! +30 XP • +1 F-Bucks",
        "cs": "Milník %d! +30 XP • +1 F-Bucks",
        "ro": "Reper %d! +30 XP • +1 F-Bucks",
        "hu": "%d. mérföldkő! +30 XP • +1 F-Bucks",
        "el": "Ορόσημο %d! +30 XP • +1 F-Bucks",
        "tr": "Kilometre taşı %d! +30 XP • +1 F-Bucks",
        "uk": "Віха %d! +30 XP • +1 F-Bucks",
        "vi": "Cột mốc %d! +30 XP • +1 F-Bucks",
        "th": "เหตุการณ์สำคัญ %d! +30 XP • +1 F-Bucks",
        "id": "Tonggak %d! +30 XP • +1 F-Bucks",
        "fil": "Hito %d! +30 XP • +1 F-Bucks",
        "hi": "माइलस्टोन %d! +30 XP • +1 F-Bucks",
        "bn": "মাইলফলক %d! +30 XP • +1 F-Bucks",
        "ta": "மைல்கல் %d! +30 XP • +1 F-Bucks",
        "te": "మైలురాయి %d! +30 XP • +1 F-Bucks",
        "ar": "محطة %d! +30 XP • +1 F-Bucks",
        "ja": "マイルストーン %d！+30 XP • +1 F-Bucks",
        "ko": "이정표 %d! +30 XP • +1 F-Bucks",
        "zh": "里程碑 %d！+30 XP • +1 F-Bucks",
        "zh-Hant": "里程碑 %d！+30 XP • +1 F-Bucks",
        "ru": "Веха %d! +30 XP • +1 F-Bucks",
    },
    "Survival next milestone fmt": {
        "de": "Noch %d richtige bis Meilenstein %d",
        "fr": "Encore %d bonnes réponses pour l’étape %d",
        "es": "%d aciertos más para el hito %d",
        "it": "Ancora %d corrette per il traguardo %d",
        "pt-BR": "Mais %d acertos para o marco %d",
        "pl": "Jeszcze %d poprawnych do kamienia %d",
        "nl": "Nog %d goed voor mijlpaal %d",
        "ca": "%d encerts més per a la fita %d",
        "sv": "%d rätt kvar till milstolpe %d",
        "cs": "Ještě %d správných do milníku %d",
        "ro": "Încă %d corecte până la reperul %d",
        "hu": "Még %d helyes a(z) %d. mérföldkőig",
        "el": "Ακόμα %d σωστές για το ορόσημο %d",
        "tr": "Kilometre taşı %2$d için %1$d doğru daha",
        "uk": "Ще %d вірних до віхи %d",
        "vi": "Còn %d câu đúng để đạt cột mốc %d",
        "th": "อีก %d ข้อถูกถึงเหตุการณ์ %d",
        "id": "Lagi %d benar menuju tonggak %d",
        "fil": "%d pang tama para sa hito %d",
        "hi": "माइलस्टोन %2$d के लिए %1$d और सही",
        "bn": "মাইলফলক %2$d-এর জন্য আর %1$dটি সঠিক",
        "ta": "மைல்கல் %2$dக்கு இன்னும் %1$d சரி",
        "te": "మైలురాయి %2$dకు మరో %1$d సరైనవి",
        "ar": "%d إجابات صحيحة أخرى للوصول إلى المحطة %d",
        "ja": "マイルストーン %2$d まであと正解 %1$d",
        "ko": "이정표 %2$d까지 정답 %1$d개 더",
        "zh": "距离里程碑 %2$d 还需答对 %1$d 题",
        "zh-Hant": "距離里程碑 %2$d 還需答對 %1$d 題",
        "ru": "Ещё %d верных до вехи %d",
    },
    "Survival result best depth fmt": {
        "de": "Persönliche Besttiefe: %d Flaggen",
        "fr": "Meilleure profondeur perso : %d drapeaux",
        "es": "Mejor profundidad personal: %d banderas",
        "it": "Record personale di profondità: %d bandiere",
        "pt-BR": "Melhor profundidade pessoal: %d bandeiras",
        "pl": "Rekord głębokości: %d flag",
        "nl": "Persoonlijk diepterecord: %d vlaggen",
        "ca": "Millor profunditat personal: %d banderes",
        "sv": "Personligt djuprekord: %d flaggor",
        "cs": "Osobní rekord hloubky: %d vlajek",
        "ro": "Record personal de adâncime: %d steaguri",
        "hu": "Személyes mélycsúcs: %d zászló",
        "el": "Προσωπικό ρεκόρ βάθους: %d σημαίες",
        "tr": "Kişisel en iyi derinlik: %d bayrak",
        "uk": "Особистий рекорд глибини: %d прапорів",
        "vi": "Kỷ lục độ sâu cá nhân: %d lá cờ",
        "th": "สถิติความลึกส่วนตัว: %d ธง",
        "id": "Rekor kedalaman pribadi: %d bendera",
        "fil": "Personal best na lalim: %d watawat",
        "hi": "व्यक्तिगत सर्वश्रेष्ठ गहराई: %d झंडे",
        "bn": "ব্যক্তিগত সেরা গভীরতা: %dটি পতাকা",
        "ta": "தனிப்பட்ட சிறந்த ஆழம்: %d கொடிகள்",
        "te": "వ్యక్తిగత ఉత్తమ లోతు: %d జండాలు",
        "ar": "أفضل عمق شخصي: %d علمًا",
        "ja": "自己ベスト深度：%d 国旗",
        "ko": "개인 최고 깊이: %d개 국기",
        "zh": "个人最佳深度：%d 面旗",
        "zh-Hant": "個人最佳深度：%d 面旗",
        "ru": "Личный рекорд глубины: %d флагов",
    },
    "Survival result combo fmt": {
        "de": "Beste Serie in diesem Lauf: %d",
        "fr": "Meilleur enchaînement cette partie : %d",
        "es": "Mejor racha en esta partida: %d",
        "it": "Miglior serie in questa partita: %d",
        "pt-BR": "Melhor sequência nesta partida: %d",
        "pl": "Najlepsza seria w tej grze: %d",
        "nl": "Beste reeks deze run: %d",
        "ca": "Millor ratxa en aquesta partida: %d",
        "sv": "Bästa serie den här omgången: %d",
        "cs": "Nejlepší série v tomto běhu: %d",
        "ro": "Cel mai bun șir în această rundă: %d",
        "hu": "Legjobb sorozat ebben a futamban: %d",
        "el": "Καλύτερο σερί σε αυτό το παιχνίδι: %d",
        "tr": "Bu koşudaki en iyi seri: %d",
        "uk": "Найкраща серія в цьому забігу: %d",
        "vi": "Chuỗi tốt nhất lượt này: %d",
        "th": "คอมโบที่ดีที่สุดในรอบนี้: %d",
        "id": "Kombo terbaik di putaran ini: %d",
        "fil": "Pinakamahusay na combo sa run na ito: %d",
        "hi": "इस रन में सबसे अच्छी लकीर: %d",
        "bn": "এই রানে সেরা কম্বো: %d",
        "ta": "இந்த ஓட்டத்தில் சிறந்த தொடர்: %d",
        "te": "ఈ రన్‌లో ఉత్తమ కాంబో: %d",
        "ar": "أفضل سلسلة في هذه الجولة: %d",
        "ja": "今回の最高コンボ：%d",
        "ko": "이번 플레이 최고 콤보: %d",
        "zh": "本局最佳连击：%d",
        "zh-Hant": "本局最佳連擊：%d",
        "ru": "Лучшая серия в забеге: %d",
    },
    "Survival result survived fmt": {
        "de": "Du hast %d Flaggen überlebt",
        "fr": "Tu as survécu à %d drapeaux",
        "es": "Has sobrevivido %d banderas",
        "it": "Hai superato %d bandiere",
        "pt-BR": "Você sobreviveu a %d bandeiras",
        "pl": "Przetrwałeś %d flag",
        "nl": "Je hebt %d vlaggen overleefd",
        "ca": "Has sobreviscut %d banderes",
        "sv": "Du överlevde %d flaggor",
        "cs": "Přežil jsi %d vlajek",
        "ro": "Ai supraviețuit %d steaguri",
        "hu": "%d zászlót éltél túl",
        "el": "Έφτασες τις %d σημαίες",
        "tr": "%d bayrak hayatta kaldın",
        "uk": "Ви дійшли до %d прапорів",
        "vi": "Bạn vượt qua %d lá cờ",
        "th": "คุณรอด %d ธง",
        "id": "Kamu bertahan %d bendera",
        "fil": "Nakalampas ka sa %d watawat",
        "hi": "आपने %d झंडे पार किए",
        "bn": "আপনি %dটি পতাকা টিকে ছিলেন",
        "ta": "நீங்கள் %d கொடிகளை கடந்தீர்கள்",
        "te": "మీరు %d జండాలను దాటారు",
        "ar": "لقد تجاوزت %d علمًا",
        "ja": "%d 国旗をクリア",
        "ko": "%d개 국기를 버텼습니다",
        "zh": "你挺过了 %d 面旗",
        "zh-Hant": "你挺過了 %d 面旗",
        "ru": "Вы дошли до %d флагов",
    },
    "Survival result stage reached fmt": {
        "de": "Erreichte Maximalstufe: %d",
        "fr": "Étape max atteinte : %d",
        "es": "Etapa máxima alcanzada: %d",
        "it": "Fase massima raggiunta: %d",
        "pt-BR": "Fase máxima alcançada: %d",
        "pl": "Maksymalny etap: %d",
        "nl": "Hoogste niveau bereikt: %d",
        "ca": "Etapa màxima assolida: %d",
        "sv": "Högsta nivå nådd: %d",
        "cs": "Dosaženo max. fáze: %d",
        "ro": "Nivel maxim atins: %d",
        "hu": "Elért max. szint: %d",
        "el": "Μέγιστο στάδιο: %d",
        "tr": "Ulaşılan en yüksek aşama: %d",
        "uk": "Макс. досягнутий етап: %d",
        "vi": "Giai đoạn cao nhất: %d",
        "th": "เวทีสูงสุดที่ถึง: %d",
        "id": "Tahap tertinggi: %d",
        "fil": "Pinakamataas na stage: %d",
        "hi": "अधिकतम स्तर: %d",
        "bn": "সর্বোচ্চ স্তর: %d",
        "ta": "அதிகபட்ச நிலை: %d",
        "te": "చేరిన గరిష్ట దశ: %d",
        "ar": "أعلى مرحلة وصلت إليها: %d",
        "ja": "到達した最高ステージ：%d",
        "ko": "도달한 최고 스테이지: %d",
        "zh": "到达的最高阶段：%d",
        "zh-Hant": "到達的最高階段：%d",
        "ru": "Макс. этап: %d",
    },
    "Survival stat correct": {
        "de": "RICHTIG",
        "fr": "CORRECT",
        "es": "CORRECTO",
        "it": "CORRETTO",
        "pt-BR": "CERTO",
        "pl": "DOBRZE",
        "nl": "GOED",
        "ca": "CORRECTE",
        "sv": "RÄTT",
        "cs": "SPRÁVNĚ",
        "ro": "CORECT",
        "hu": "HELYES",
        "el": "ΣΩΣΤΌ",
        "tr": "DOĞRU",
        "uk": "ВІРНО",
        "vi": "ĐÚNG",
        "th": "ถูก",
        "id": "BENAR",
        "fil": "TAMA",
        "hi": "सही",
        "bn": "সঠিক",
        "ta": "சரி",
        "te": "సరైనది",
        "ar": "صحيح",
        "ja": "正解",
        "ko": "정답",
        "zh": "正确",
        "zh-Hant": "正確",
        "ru": "ВЕРНО",
    },
    "Survival intro description": {
        "de": "Beantworte nacheinander viele Flaggen. Falsche Antworten kosten Leben. Die Schwierigkeit steigt — schlag deinen Tiefenrekord.",
        "fr": "Enchaîne les drapeaux. Les erreurs coûtent des vies. La difficulté augmente — bats ton record de profondeur.",
        "es": "Responde banderas una tras otra. Los errores cuestan vidas. La dificultad sube — supera tu récord de profundidad.",
        "it": "Rispondi a una bandiera dopo l’altra. Gli errori costano vite. La difficoltà sale — batti il tuo record di profondità.",
        "pt-BR": "Acerte bandeira após bandeira. Erros custam vidas. A dificuldade sobe — supere seu recorde de profundidade.",
        "pl": "Odpowiadaj na flagi jedna po drugiej. Błędy kosztują życia. Poziom rośnie — pobij rekord głębokości.",
        "nl": "Beantwoord vlag na vlag. Fouten kosten levens. Het wordt moeilijker — verbeter je diepterecord.",
        "ca": "Encerta banderes l’una rere l’altra. Els errors costen vides. La dificultat puja — bate el teu rècord de profunditat.",
        "sv": "Svara flagga efter flagga. Fel kostar liv. Svårigheten ökar — slå ditt djuprekord.",
        "cs": "Odpovídej na vlajky za sebou. Chyby berou životy. Obtížnost roste — překonej svůj rekord hloubky.",
        "ro": "Răspunde la steag după steag. Greșelile costă vieți. Dificultatea crește — depășește recordul de adâncime.",
        "hu": "Válaszolj zászlóról zászlóra. A hibák életbe kerülnek. Nehezedik a játék — döntsd meg a mélyrekordod.",
        "el": "Απάντησε σημαία τη σημαία. Τα λάθη κοστίζουν ζωές. Αυξάνεται η δυσκολία — σπάσε το ρεκόρ βάθους σου.",
        "tr": "Bayrakları art arda bil. Yanlışlar can kaybettirir. Zorluk artar — derinlik rekorunu kır.",
        "uk": "Відповідай на прапори один за одним. Помилки забирають життя. Складність росте — побий рекорд глибини.",
        "vi": "Trả lời từng lá cờ. Sai sẽ mất mạng. Độ khó tăng — phá kỷ lục độ sâu của bạn.",
        "th": "ตอบธงทีละข้อ ตอบผิดเสียชีวิต ความยากขึ้นเรื่อย ๆ — ทำลายสถิติความลึกของคุณ",
        "id": "Jawab bendera demi bendera. Salah mengurangi nyawa. Kesulitan naik — pecahkan rekor kedalamanmu.",
        "fil": "Sagutin ang mga watawat isa-isa. Mali ay may kapalit na buhay. Tumitindi ang hirap — sirain ang record mo sa lalim.",
        "hi": "झंडियों का एक के बाद एक जवाब दें। गलती पर जान जाती है। कठिनाई बढ़ती है — अपना गहराई रिकॉर्ड तोड़ें।",
        "bn": "একের পর এক পতাকার উত্তর দিন। ভুলে জীবন যায়। কঠিনতা বাড়ে — আপনার গভীরতার রেকর্ড ভাঙুন।",
        "ta": "கொடிகளுக்கு ஒன்றன் பின் ஒன்றாக பதிலளிக்கவும். தவறுகள் உயிர்களைப் பறிக்கும். சிரமம் அதிகரிக்கும் — உங்கள் ஆழ சாதனையை முறியடிக்கவும்.",
        "te": "జండాలకు ఒక్కొక్కటిగా సమాధానం ఇవ్వండి. తప్పులకు జీవితాలు పోతాయి. కష్టం పెరుగుతుంది — మీ లోతు రికార్డ్‌ను బద్దలు కొట్టండి.",
        "ar": "أجب عن الأعلام واحدًا تلو الآخر. الخطأ يكلفك حياتًا. تزداد الصعوبة — حطّم رقمك القياسي في العمق.",
        "ja": "国旗に次々と答えよう。不正解でライフが減り、難易度は上がる — 深度の記録を更新しよう。",
        "ko": "국기를 하나씩 맞히세요. 오답은 생명을 잃게 하고 난이도는 올라갑니다 — 깊이 기록을 갱신하세요.",
        "zh": "逐题辨认国旗。答错会失去生命，难度会上升——打破你的深度纪录。",
        "zh-Hant": "逐題辨認國旗。答錯會失去生命，難度會上升——打破你的深度紀錄。",
        "ru": "Флаги один за другим. Ошибки отнимают жизни. Сложность растёт — бейте рекорд глубины.",
    },
    "Survival intro lives title": {
        "de": "Startleben",
        "fr": "Vies de départ",
        "es": "Vidas iniciales",
        "it": "Vite iniziali",
        "pt-BR": "Vidas iniciais",
        "pl": "Życia na start",
        "nl": "Startlevens",
        "ca": "Vides inicials",
        "sv": "Startliv",
        "cs": "Startovní životy",
        "ro": "Vieți de start",
        "hu": "Kezdő életek",
        "el": "Αρχικές ζωές",
        "tr": "Başlangıç canları",
        "uk": "Життя на старті",
        "vi": "Mạng ban đầu",
        "th": "ชีวิตเริ่มต้น",
        "id": "Nyawa awal",
        "fil": "Simulang buhay",
        "hi": "शुरुआती जीवन",
        "bn": "শুরুর জীবন",
        "ta": "தொடக்க உயிர்கள்",
        "te": "ప్రారంభ జీవితాలు",
        "ar": "حيوات البداية",
        "ja": "スタート時のライフ",
        "ko": "시작 생명",
        "zh": "起始生命",
        "zh-Hant": "起始生命",
        "ru": "Жизни в начале",
    },
    "Survival intro best depth title": {
        "de": "Beste Tiefe",
        "fr": "Meilleure profondeur",
        "es": "Mejor profundidad",
        "it": "Miglior profondità",
        "pt-BR": "Melhor profundidade",
        "pl": "Najlepsza głębokość",
        "nl": "Beste diepte",
        "ca": "Millor profunditat",
        "sv": "Bästa djup",
        "cs": "Nejlepší hloubka",
        "ro": "Cea mai bună adâncime",
        "hu": "Legjobb mélység",
        "el": "Καλύτερο βάθος",
        "tr": "En iyi derinlik",
        "uk": "Найкраща глибина",
        "vi": "Độ sâu tốt nhất",
        "th": "ความลึกที่ดีที่สุด",
        "id": "Kedalaman terbaik",
        "fil": "Pinakamahusay na lalim",
        "hi": "सर्वश्रेष्ठ गहराई",
        "bn": "সেরা গভীরতা",
        "ta": "சிறந்த ஆழம்",
        "te": "ఉత్తమ లోతు",
        "ar": "أفضل عمق",
        "ja": "ベスト深度",
        "ko": "최고 깊이",
        "zh": "最佳深度",
        "zh-Hant": "最佳深度",
        "ru": "Лучшая глубина",
    },
    "Survival intro choices title": {
        "de": "Antwortmöglichkeiten",
        "fr": "Choix",
        "es": "Opciones",
        "it": "Scelte",
        "pt-BR": "Opções",
        "pl": "Opcje",
        "nl": "Keuzes",
        "ca": "Opcions",
        "sv": "Val",
        "cs": "Možnosti",
        "ro": "Variante",
        "hu": "Választási lehetőségek",
        "el": "Επιλογές",
        "tr": "Seçenekler",
        "uk": "Варіанти",
        "vi": "Lựa chọn",
        "th": "ตัวเลือก",
        "id": "Pilihan",
        "fil": "Mga pagpipilian",
        "hi": "विकल्प",
        "bn": "বিকল্প",
        "ta": "விருப்பங்கள்",
        "te": "ఎంపికలు",
        "ar": "الخيارات",
        "ja": "選択肢",
        "ko": "선택지",
        "zh": "选项",
        "zh-Hant": "選項",
        "ru": "Варианты",
    },
    "Survival intro timer title": {
        "de": "Timer",
        "fr": "Chronomètres",
        "es": "Temporizadores",
        "it": "Timer",
        "pt-BR": "Cronômetros",
        "pl": "Timery",
        "nl": "Timers",
        "ca": "Temporitzadors",
        "sv": "Timers",
        "cs": "Časovače",
        "ro": "Cronometre",
        "hu": "Időzítők",
        "el": "Χρονόμετρα",
        "tr": "Süreler",
        "uk": "Таймери",
        "vi": "Hẹn giờ",
        "th": "ตัวจับเวลา",
        "id": "Timer",
        "fil": "Mga timer",
        "hi": "टाइमर",
        "bn": "টাইমার",
        "ta": "டைமர்கள்",
        "te": "టైమర్లు",
        "ar": "المؤقتات",
        "ja": "タイマー",
        "ko": "타이머",
        "zh": "计时",
        "zh-Hant": "計時",
        "ru": "Таймеры",
    },
    "Survival intro timer value": {
        "de": "Wie im Klassik-Modus",
        "fr": "Comme en mode Classique",
        "es": "Como en Clásico",
        "it": "Come in Classica",
        "pt-BR": "Como no Clássico",
        "pl": "Jak w trybie Klasycznym",
        "nl": "Zoals Klassiek",
        "ca": "Com al mode Clàssic",
        "sv": "Som i Klassiskt",
        "cs": "Jako v Klasickém",
        "ro": "Ca în Clasic",
        "hu": "Mint a Klasszikus módban",
        "el": "Όπως στην Κλασική",
        "tr": "Klasik gibi",
        "uk": "Як у Класиці",
        "vi": "Giống chế độ Cổ điển",
        "th": "เหมือนโหมดคลาสสิก",
        "id": "Seperti Klasik",
        "fil": "Tulad ng Classic",
        "hi": "क्लासिक जैसा",
        "bn": "ক্লাসিকের মতো",
        "ta": "கிளாசிக் போல",
        "te": "క్లాసిక్ లాగా",
        "ar": "مثل الوضع الكلاسيكي",
        "ja": "クラシックと同じ",
        "ko": "클래식과 동일",
        "zh": "与经典模式相同",
        "zh-Hant": "與經典模式相同",
        "ru": "Как в Классике",
    },
    "Survival weekly title": {
        "de": "Wöchentliche Survival-Herausforderung",
        "fr": "Défi Survie hebdomadaire",
        "es": "Reto semanal de supervivencia",
        "it": "Sfida settimanale Sopravvivenza",
        "pt-BR": "Desafio semanal de Sobrevivência",
        "pl": "Tygodniowe wyzwanie Survival",
        "nl": "Wekelijkse Survival-uitdaging",
        "ca": "Repte setmanal de supervivència",
        "sv": "Veckoutmaning Survival",
        "cs": "Týdenní Survival výzva",
        "ro": "Provocare săptămânală Supraviețuire",
        "hu": "Heti túlélő kihívás",
        "el": "Εβδομαδιαία πρόκληση Επιβίωσης",
        "tr": "Haftalık Hayatta Kalma görevi",
        "uk": "Тижневий челендж виживання",
        "vi": "Thử thách Sinh tồn hàng tuần",
        "th": "ความท้าทายเอาชีวิตรอดรายสัปดาห์",
        "id": "Tantangan Survival mingguan",
        "fil": "Lingguhang Survival challenge",
        "hi": "साप्ताहिक सर्वाइवल चुनौती",
        "bn": "সাপ্তাহিক সারভাইভাল চ্যালেঞ্জ",
        "ta": "வாராந்திர உயிர் பிழைப்பு சவால்",
        "te": "వారపు సర్వైవల్ సవాలు",
        "ar": "تحدي البقاء الأسبوعي",
        "ja": "ウィークリーサバイバルチャレンジ",
        "ko": "주간 서바이벌 챌린지",
        "zh": "每周生存挑战",
        "zh-Hant": "每週生存挑戰",
        "ru": "Недельный челлендж Survival",
    },
    "Survival weekly target fmt": {
        "de": "Erreiche in einem Lauf in dieser Woche %d überlebte Flaggen.",
        "fr": "Atteins %d drapeaux survécus en une partie cette semaine.",
        "es": "Alcanza %d banderas sobrevividas en una partida esta semana.",
        "it": "Raggiungi %d bandiere in una partita questa settimana.",
        "pt-BR": "Alcance %d bandeiras sobrevividas em uma partida nesta semana.",
        "pl": "W jednej grze w tym tygodniu przetrwaj %d flag.",
        "nl": "Behaal %d overleefde vlaggen in één run deze week.",
        "ca": "Aconsegueix %d banderes sobreviscudes en una partida aquesta setmana.",
        "sv": "Överlev %d flaggor i en omgång den här veckan.",
        "cs": "V jednom běhu tento týden přežij %d vlajek.",
        "ro": "Într-o rundă săptămâna aceasta supraviețuiește la %d steaguri.",
        "hu": "Ezen a héten egy futamban élj túl %d zászlót.",
        "el": "Αυτή την εβδομάδα σε ένα παιχνίδι επέζησε %d σημαίες.",
        "tr": "Bu hafta tek koşuda %d bayrak hayatta kal.",
        "uk": "За один забіг на цьому тижні виживіть %d прапорів.",
        "vi": "Trong một lượt tuần này, vượt qua %d lá cờ.",
        "th": "สัปดาห์นี้ให้รอด %d ธงในรอบเดียว",
        "id": "Dalam satu putaran minggu ini, bertahan %d bendera.",
        "fil": "Sa isang run ngayong linggo, makalampas sa %d watawat.",
        "hi": "इस सप्ताह एक रन में %d झंडे पार करें।",
        "bn": "এই সপ্তাহে এক রানে %dটি পতাকা টিকে থাকুন।",
        "ta": "இந்த வாரம் ஒரு ஓட்டத்தில் %d கொடிகளை கடக்கவும்.",
        "te": "ఈ వారం ఒకే రన్‌లో %d జండాలను దాటండి.",
        "ar": "احرز %d علمًا متجاوزًا في جولة واحدة هذا الأسبوع.",
        "ja": "今週1プレイで %d 国旗をクリアしよう。",
        "ko": "이번 주 한 판에서 %d개 국기를 버티세요.",
        "zh": "本周在一局内存活 %d 面旗。",
        "zh-Hant": "本週在一局內存活 %d 面旗。",
        "ru": "За одну попытку на этой неделе выживите %d флагов.",
    },
    "Survival weekly best fmt": {
        "de": "Dein Bestwert diese Woche: %d Flaggen",
        "fr": "Ton meilleur score cette semaine : %d drapeaux",
        "es": "Tu mejor marca esta semana: %d banderas",
        "it": "Il tuo miglior punteggio questa settimana: %d bandiere",
        "pt-BR": "Seu melhor nesta semana: %d bandeiras",
        "pl": "Twój najlepszy wynik w tym tygodniu: %d flag",
        "nl": "Je beste deze week: %d vlaggen",
        "ca": "El teu millor aquesta setmana: %d banderes",
        "sv": "Ditt bästa den här veckan: %d flaggor",
        "cs": "Tvůj nejlepší tento týden: %d vlajek",
        "ro": "Cel mai bun săptămâna aceasta: %d steaguri",
        "hu": "A heti legjobbod: %d zászló",
        "el": "Το καλύτερό σου αυτή την εβδομάδα: %d σημαίες",
        "tr": "Bu haftaki en iyisi: %d bayrak",
        "uk": "Ваш найкращий результат за тиждень: %d прапорів",
        "vi": "Tốt nhất tuần này của bạn: %d lá cờ",
        "th": "ดีที่สุดของคุณในสัปดาห์นี้: %d ธง",
        "id": "Terbaikmu minggu ini: %d bendera",
        "fil": "Pinakamahusay mo ngayong linggo: %d watawat",
        "hi": "इस सप्ताह आपका सर्वश्रेष्ठ: %d झंडे",
        "bn": "এই সপ্তাহে আপনার সেরা: %dটি পতাকা",
        "ta": "இந்த வாரம் உங்கள் சிறந்தது: %d கொடிகள்",
        "te": "ఈ వారం మీ ఉత్తమం: %d జండాలు",
        "ar": "أفضل نتيجة لك هذا الأسبوع: %d علمًا",
        "ja": "今週のベスト：%d 国旗",
        "ko": "이번 주 최고 기록: %d개 국기",
        "zh": "本周最佳：%d 面旗",
        "zh-Hant": "本週最佳：%d 面旗",
        "ru": "Ваш лучший результат на неделе: %d флагов",
    },
    "Survival weekly reward claimed": {
        "de": "Wöchentlicher Bonus eingelöst (+1000 XP)",
        "fr": "Bonus hebdomadaire obtenu (+1000 XP)",
        "es": "Bono semanal reclamado (+1000 XP)",
        "it": "Bonus settimanale ottenuto (+1000 XP)",
        "pt-BR": "Bônus semanal resgatado (+1000 XP)",
        "pl": "Tygodniowy bonus odebrany (+1000 XP)",
        "nl": "Wekelijkse bonus geclaimd (+1000 XP)",
        "ca": "Bonus setmanal reclamat (+1000 XP)",
        "sv": "Veckobonus hämtad (+1000 XP)",
        "cs": "Týdenní bonus vyzvednut (+1000 XP)",
        "ro": "Bonus săptămânal revendicat (+1000 XP)",
        "hu": "Heti bónusz beváltva (+1000 XP)",
        "el": "Εβδομαδιαίο μπόνους (+1000 XP)",
        "tr": "Haftalık bonus alındı (+1000 XP)",
        "uk": "Тижневий бонус отримано (+1000 XP)",
        "vi": "Đã nhận thưởng tuần (+1000 XP)",
        "th": "รับโบนัสรายสัปดาห์แล้ว (+1000 XP)",
        "id": "Bonus mingguan diklaim (+1000 XP)",
        "fil": "Nakuha ang lingguhang bonus (+1000 XP)",
        "hi": "साप्ताहिक बोनस मिला (+1000 XP)",
        "bn": "সাপ্তাহিক বোনাস দাবি করা হয়েছে (+1000 XP)",
        "ta": "வாராந்திர போனஸ் பெறப்பட்டது (+1000 XP)",
        "te": "వారపు బోనస్ క్లెయిమ్ చేయబడింది (+1000 XP)",
        "ar": "تم استلام المكافأة الأسبوعية (+1000 XP)",
        "ja": "ウィークリーボーナス獲得（+1000 XP）",
        "ko": "주간 보너스 수령 (+1000 XP)",
        "zh": "已领取每周奖励（+1000 XP）",
        "zh-Hant": "已領取每週獎勵（+1000 XP）",
        "ru": "Недельный бонус получен (+1000 XP)",
    },
    "Survival weekly reward hint": {
        "de": "Erreiche das Ziel einmal pro Woche für +1000 XP.",
        "fr": "Atteins l’objectif une fois par semaine pour +1000 XP.",
        "es": "Alcanza el objetivo una vez por semana para +1000 XP.",
        "it": "Raggiungi l’obiettivo una volta a settimana per +1000 XP.",
        "pt-BR": "Complete a meta uma vez por semana para +1000 XP.",
        "pl": "Osiągnij cel raz w tygodniu, by dostać +1000 XP.",
        "nl": "Haal het doel één keer per week voor +1000 XP.",
        "ca": "Assoleix l’objectiu un cop per setmana per +1000 XP.",
        "sv": "Nå målet en gång i veckan för +1000 XP.",
        "cs": "Splň cíl jednou týdně za +1000 XP.",
        "ro": "Atinge obiectivul o dată pe săptămână pentru +1000 XP.",
        "hu": "Hetente egyszer érd el a célt +1000 XP-ért.",
        "el": "Πέτυχε τον στόχο μία φορά την εβδομάδα για +1000 XP.",
        "tr": "Haftada bir kez hedefe ulaş, +1000 XP kazan.",
        "uk": "Досягайте мети раз на тиждень — +1000 XP.",
        "vi": "Đạt mục tiêu mỗi tuần một lần để +1000 XP.",
        "th": "ทำเป้าหมายให้ได้สัปดาห์ละครั้งเพื่อ +1000 XP",
        "id": "Capai target sekali seminggu untuk +1000 XP.",
        "fil": "Abutin ang goal minsan kada linggo para sa +1000 XP.",
        "hi": "हर सप्ताह एक बार लक्ष्य पूरा करें (+1000 XP)।",
        "bn": "প্রতি সপ্তাহে একবার লক্ষ্যে পৌঁছান +1000 XP-এর জন্য।",
        "ta": "வாரத்திற்கு ஒருமுறை இலக்கை அடையுங்கள் +1000 XP-க்கு.",
        "te": "వారానికి ఒకసారి లక్ష్యాన్ని చేరుకోండి +1000 XP కోసం.",
        "ar": "حقق الهدف مرة أسبوعيًا للحصول على +1000 XP.",
        "ja": "週に1回目標を達成すると +1000 XP。",
        "ko": "주 1회 목표를 달성하면 +1000 XP.",
        "zh": "每周达成一次目标可获得 +1000 XP。",
        "zh-Hant": "每週達成一次目標可獲得 +1000 XP。",
        "ru": "Достигните цели раз в неделю: +1000 XP.",
    },
}


def build_overlay() -> dict[str, dict[str, str]]:
    key_order = [
        "Answer as many flags as possible before time runs out",
        "Duration",
        "Wrong answer penalty",
        "5 correct in a row bonus",
        "Best combo",
        "TC stat best combo",
        "Start",
        "New record!",
        "Day leaderboard place",
        "Week leaderboard place",
        "Share Survival headline",
        "Survival mode short description",
        "Survival difficulty blurb fmt",
        "Survival depth header",
        "Survival stage fmt",
        "Survival bonus life streak",
        "Survival milestone banner fmt",
        "Survival next milestone fmt",
        "Survival result best depth fmt",
        "Survival result combo fmt",
        "Survival result survived fmt",
        "Survival result stage reached fmt",
        "Survival stat correct",
        "Survival intro description",
        "Survival intro lives title",
        "Survival intro best depth title",
        "Survival intro choices title",
        "Survival intro timer title",
        "Survival intro timer value",
        "Survival weekly title",
        "Survival weekly target fmt",
        "Survival weekly best fmt",
        "Survival weekly reward claimed",
        "Survival weekly reward hint",
    ]
    out: dict[str, dict[str, str]] = {lang: {} for lang in ALL_LANGS}
    for key in key_order:
        per = T[key]
        for lang in ALL_LANGS:
            if lang not in per:
                raise KeyError(f"missing {lang!r} for key {key!r}")
            out[lang][key] = per[lang]
    return out


OVERLAY = build_overlay()

