#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Вставляет ключи оверлея «жизни закончились» после строки Unfortunately... во все Resources/*.lproj."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "World Arena. Flags" / "Resources"

MARKER = '"Unfortunately you ran out of lives this time. Try again or come back later."'
CHECK = '"Out of lives headline 1"'


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def block_for(lang: str) -> str:
    t = TRANSLATIONS[lang]
    lines = [
        f'"Out of lives headline 1" = "{esc(t["h1"])}";',
        f'"Out of lives headline 2" = "{esc(t["h2"])}";',
        f'"Out of lives headline 3" = "{esc(t["h3"])}";',
        f'"Out of lives headline 4" = "{esc(t["h4"])}";',
        f'"Out of lives headline 5" = "{esc(t["h5"])}";',
        f'"Out of lives headline 6" = "{esc(t["h6"])}";',
        f'"Out of lives headline 7" = "{esc(t["h7"])}";',
        f'"Out of lives continue subtitle" = "{esc(t["sub"])}";',
        f'"Continue with bonus lives" = "{esc(t["cont"])}";',
        f'"Out of lives perk resume" = "{esc(t["pr"])}";',
        f'"Out of lives perk progress" = "{esc(t["pp"])}";',
        f'"Out of lives urgency" = "{esc(t["ur"])}";',
        f'"Ad-free with Premium" = "{esc(t["ad"])}";',
        f'"Out of lives continue premium" = "{esc(t["cp"])}";',
    ]
    return "\n".join(lines) + "\n"


# Ключи в коде — английские; значения — перевод для каждого языка. %d — для String(format:).
TRANSLATIONS: dict[str, dict[str, str]] = {
    "ru": {
        "h1": "Ты почти у цели! 🚀",
        "h2": "Продолжим?",
        "h3": "Остался последний шаг!",
        "h4": "Так близко!",
        "h5": "Не останавливайся!",
        "h6": "Ещё раунд?",
        "h7": "Держи серию!",
        "sub": "Продолжим с этого места?",
        "cont": "Продолжить (+%d жизней)",
        "pr": "+%d жизни — продолжишь с этого же места",
        "pp": "Прогресс не потеряется",
        "ur": "Быстрее — не теряй прогресс!",
        "ad": "Без рекламы — с Premium",
        "cp": "Продолжить с Premium",
    },
    "uk": {
        "h1": "Ти майже пройшов! 🚀",
        "h2": "Давай продовжимо?",
        "h3": "Залишився останній крок!",
        "h4": "Так близько!",
        "h5": "Не зупиняйся!",
        "h6": "Ще один раунд?",
        "h7": "Тримай серію!",
        "sub": "Продовжимо з цього місця?",
        "cont": "Продовжити (+%d життів)",
        "pr": "+%d життя — продовжиш з цього ж місця",
        "pp": "Прогрес не втратиш",
        "ur": "Швидше — не губи прогрес!",
        "ad": "Без реклами — з Premium",
        "cp": "Продовжити з Premium",
    },
    "de": {
        "h1": "Du hast es fast geschafft! 🚀",
        "h2": "Machen wir weiter?",
        "h3": "Nur noch ein Schritt!",
        "h4": "So nah dran!",
        "h5": "Hör jetzt nicht auf!",
        "h6": "Noch eine Runde?",
        "h7": "Halte deine Serie!",
        "sub": "Weiterspielen von hier?",
        "cont": "Weiter (+%d Leben)",
        "pr": "+%d Leben — genau da weitermachen, wo du aufgehört hast",
        "pp": "Dein Fortschritt bleibt erhalten",
        "ur": "Schnell — behalte deinen Fortschritt!",
        "ad": "Werbefrei mit Premium",
        "cp": "Mit Premium weitermachen",
    },
    "fr": {
        "h1": "Tu y es presque ! 🚀",
        "h2": "On continue ?",
        "h3": "Plus qu'une étape !",
        "h4": "Si proche !",
        "h5": "Ne t'arrête pas !",
        "h6": "Encore une manche ?",
        "h7": "Garde ta série !",
        "sub": "On reprend d'ici ?",
        "cont": "Continuer (+%d vies)",
        "pr": "+%d vies — tu reprends exactement où tu t'es arrêté",
        "pp": "Tu ne perds pas ta progression",
        "ur": "Vite — garde ta progression !",
        "ad": "Sans pub avec Premium",
        "cp": "Continuer avec Premium",
    },
    "es": {
        "h1": "¡Casi lo logras! 🚀",
        "h2": "¿Seguimos?",
        "h3": "¡Queda un paso!",
        "h4": "¡Tan cerca!",
        "h5": "¡No pares ahora!",
        "h6": "¿Otra ronda?",
        "h7": "¡Mantén la racha!",
        "sub": "¿Continuamos desde aquí?",
        "cont": "Continuar (+%d vidas)",
        "pr": "+%d vidas — sigues justo donde lo dejaste",
        "pp": "No perderás el progreso",
        "ur": "¡Rápido — no pierdas el progreso!",
        "ad": "Sin anuncios con Premium",
        "cp": "Continuar con Premium",
    },
    "it": {
        "h1": "Ci sei quasi! 🚀",
        "h2": "Continuiamo?",
        "h3": "Manca un passo!",
        "h4": "Così vicino!",
        "h5": "Non fermarti ora!",
        "h6": "Ancora un round?",
        "h7": "Mantieni la serie!",
        "sub": "Riprendiamo da qui?",
        "cont": "Continua (+%d vite)",
        "pr": "+%d vite — riparti da dove ti sei fermato",
        "pp": "Non perderai i progressi",
        "ur": "Veloce — non perdere i progressi!",
        "ad": "Senza pubblicità con Premium",
        "cp": "Continua con Premium",
    },
    "pt-BR": {
        "h1": "Você quase conseguiu! 🚀",
        "h2": "Vamos continuar?",
        "h3": "Falta só um passo!",
        "h4": "Tão perto!",
        "h5": "Não pare agora!",
        "h6": "Mais uma rodada?",
        "h7": "Mantenha a sequência!",
        "sub": "Continuar daqui?",
        "cont": "Continuar (+%d vidas)",
        "pr": "+%d vidas — você volta exatamente de onde parou",
        "pp": "Você não perde o progresso",
        "ur": "Rápido — não perca o progresso!",
        "ad": "Sem anúncios com Premium",
        "cp": "Continuar com Premium",
    },
    "pl": {
        "h1": "Już prawie! 🚀",
        "h2": "Gramy dalej?",
        "h3": "Został ostatni krok!",
        "h4": "Tak blisko!",
        "h5": "Nie zatrzymuj się!",
        "h6": "Jeszcze jedna runda?",
        "h7": "Utrzymaj passę!",
        "sub": "Kontynuujemy stąd?",
        "cont": "Kontynuuj (+%d żyć)",
        "pr": "+%d żyć — wracasz dokładnie w to samo miejsce",
        "pp": "Nie stracisz postępu",
        "ur": "Szybko — nie trać postępu!",
        "ad": "Bez reklam z Premium",
        "cp": "Kontynuuj z Premium",
    },
    "nl": {
        "h1": "Je bent er bijna! 🚀",
        "h2": "Gaan we verder?",
        "h3": "Nog één stap!",
        "h4": "Zo dichtbij!",
        "h5": "Stop nu niet!",
        "h6": "Nog een ronde?",
        "h7": "Houd je reeks vast!",
        "sub": "Verdergaan vanaf hier?",
        "cont": "Doorgaan (+%d levens)",
        "pr": "+%d levens — je gaat verder waar je stopte",
        "pp": "Je verliest je voortgang niet",
        "ur": "Snel — behoud je voortgang!",
        "ad": "Reclamevrij met Premium",
        "cp": "Doorgaan met Premium",
    },
    "ca": {
        "h1": "Gairebé ho tens! 🚀",
        "h2": "Seguim?",
        "h3": "Només queda un pas!",
        "h4": "Tan a prop!",
        "h5": "No pares ara!",
        "h6": "Una altra ronda?",
        "h7": "Mantén la ratxa!",
        "sub": "Continuem des d'aquí?",
        "cont": "Continuar (+%d vides)",
        "pr": "+%d vides — continues just on ho has deixat",
        "pp": "No perdràs el progrés",
        "ur": "Ràpid — no perdis el progrés!",
        "ad": "Sense anuncis amb Premium",
        "cp": "Continuar amb Premium",
    },
    "zh": {
        "h1": "你快成功了！🚀",
        "h2": "要继续吗？",
        "h3": "还差最后一步！",
        "h4": "就差一点！",
        "h5": "别停下！",
        "h6": "再来一局？",
        "h7": "保持连胜！",
        "sub": "从这里继续？",
        "cont": "继续（+%d 条生命）",
        "pr": "+%d 条生命 — 从你离开的地方继续",
        "pp": "进度不会丢失",
        "ur": "快点 — 保住进度！",
        "ad": "Premium 免广告",
        "cp": "使用 Premium 继续",
    },
    "zh-Hant": {
        "h1": "你快成功了！🚀",
        "h2": "要繼續嗎？",
        "h3": "還差最後一步！",
        "h4": "就差一點！",
        "h5": "別停下！",
        "h6": "再來一局？",
        "h7": "保持連勝！",
        "sub": "從這裡繼續？",
        "cont": "繼續（+%d 條生命）",
        "pr": "+%d 條生命 — 從你離開的地方繼續",
        "pp": "進度不會遺失",
        "ur": "快點 — 保住進度！",
        "ad": "Premium 免廣告",
        "cp": "使用 Premium 繼續",
    },
    "ja": {
        "h1": "あと少し！🚀",
        "h2": "続けますか？",
        "h3": "ラスト一歩！",
        "h4": "もうすぐ！",
        "h5": "ここで止めないで！",
        "h6": "もう一回？",
        "h7": "連勝をキープ！",
        "sub": "ここから続ける？",
        "cont": "続ける（ライフ +%d）",
        "pr": "ライフ +%d — 中断したところから再開",
        "pp": "進行状況は失われません",
        "ur": "急いで — 進行を守ろう！",
        "ad": "Premium で広告なし",
        "cp": "Premium で続ける",
    },
    "ko": {
        "h1": "거의 다 왔어요! 🚀",
        "h2": "계속할까요?",
        "h3": "마지막 한 걸음!",
        "h4": "아주 가까워요!",
        "h5": "지금 멈추지 마세요!",
        "h6": "한 판 더?",
        "h7": "연승을 이어가요!",
        "sub": "여기서 이어할까요?",
        "cont": "계속하기 (생명 +%d)",
        "pr": "생명 +%d — 멈춘 그 자리에서 이어갑니다",
        "pp": "진행 상황을 잃지 않아요",
        "ur": "서둘러 — 진행을 지키세요!",
        "ad": "Premium으로 광고 없이",
        "cp": "Premium으로 계속",
    },
    "ar": {
        "h1": "أوشكت على النجاح! 🚀",
        "h2": "نكمل؟",
        "h3": "بقي خطوة أخيرة!",
        "h4": "قريب جدًا!",
        "h5": "لا تتوقف الآن!",
        "h6": "جولة أخرى؟",
        "h7": "حافظ على سلسلتك!",
        "sub": "نتابع من هنا؟",
        "cont": "متابعة (+%d أرواح)",
        "pr": "+%d أرواح — تكمل من حيث توقفت",
        "pp": "لن تفقد تقدمك",
        "ur": "بسرعة — احتفظ بتقدمك!",
        "ad": "بدون إعلانات مع Premium",
        "cp": "المتابعة مع Premium",
    },
    "bn": {
        "h1": "প্রায় হয়ে গেছে! 🚀",
        "h2": "চালিয়ে যাবেন?",
        "h3": "শেষ ধাপ বাকি!",
        "h4": "এত কাছে!",
        "h5": "এখন থামবেন না!",
        "h6": "আরেক রাউন্ড?",
        "h7": "স্ট্রিক ধরে রাখুন!",
        "sub": "এখান থেকে চালিয়ে যাবেন?",
        "cont": "চালিয়ে যান (+%d জীবন)",
        "pr": "+%d জীবন — যেখানে থেমেছিলেন সেখান থেকেই",
        "pp": "আপনার অগ্রগতি হারাবে না",
        "ur": "তাড়াতাড়ি — অগ্রগতি বাঁচান!",
        "ad": "Premium-এ বিজ্ঞাপন ছাড়া",
        "cp": "Premium দিয়ে চালিয়ে যান",
    },
    "cs": {
        "h1": "Už to skoro máš! 🚀",
        "h2": "Pokračujeme?",
        "h3": "Zbývá poslední krok!",
        "h4": "Tak blízko!",
        "h5": "Teď nepřestávej!",
        "h6": "Ještě jedno kolo?",
        "h7": "Udrž sérii!",
        "sub": "Pokračovat odsud?",
        "cont": "Pokračovat (+%d životů)",
        "pr": "+%d životů — pokračuješ přesně tam, kde jsi skončil",
        "pp": "Nepřijdeš o postup",
        "ur": "Rychle — nenech si vzít postup!",
        "ad": "Bez reklam s Premium",
        "cp": "Pokračovat s Premium",
    },
    "el": {
        "h1": "Σχεδόν τα κατάφερες! 🚀",
        "h2": "Συνεχίζουμε;",
        "h3": "Μένει ένα βήμα!",
        "h4": "Τόσο κοντά!",
        "h5": "Μη σταματάς τώρα!",
        "h6": "Άλλος ένας γύρος;",
        "h7": "Κράτα το σερί!",
        "sub": "Συνέχεια από εδώ;",
        "cont": "Συνέχεια (+%d ζωές)",
        "pr": "+%d ζωές — συνεχίζεις ακριβώς από εκεί που σταμάτησες",
        "pp": "Δεν χάνεις την πρόοδο",
        "ur": "Γρήγορα — κράτα την πρόοδο!",
        "ad": "Χωρίς διαφημίσεις με Premium",
        "cp": "Συνέχεια με Premium",
    },
    "fil": {
        "h1": "Malapit ka na! 🚀",
        "h2": "Ituloy natin?",
        "h3": "Isang hakbang na lang!",
        "h4": "Ang lapit!",
        "h5": "Huwag tumigil ngayon!",
        "h6": "Isa pang round?",
        "h7": "Panatilihin ang streak!",
        "sub": "Ituloy mula rito?",
        "cont": "Magpatuloy (+%d buhay)",
        "pr": "+%d buhay — magpapatuloy ka kung saan ka huminto",
        "pp": "Hindi mawawala ang progreso mo",
        "ur": "Bilisan — huwag mawala ang progreso!",
        "ad": "Walang ad sa Premium",
        "cp": "Magpatuloy sa Premium",
    },
    "hi": {
        "h1": "लगभग हो गया! 🚀",
        "h2": "आगे बढ़ें?",
        "h3": "आखिरी कदम बाकी!",
        "h4": "इतना करीब!",
        "h5": "अभी मत रुकें!",
        "h6": "एक और राउंड?",
        "h7": "सिलसिला जारी रखें!",
        "sub": "यहीं से जारी रखें?",
        "cont": "जारी रखें (+%d जीवन)",
        "pr": "+%d जीवन — जहाँ रुके थे वहीं से",
        "pp": "प्रगति नहीं खोएंगे",
        "ur": "जल्दी करें — प्रगति बचाएं!",
        "ad": "Premium के साथ बिना विज्ञापन",
        "cp": "Premium से जारी रखें",
    },
    "hu": {
        "h1": "Majdnem megvan! 🚀",
        "h2": "Folytatjuk?",
        "h3": "Már csak egy lépés!",
        "h4": "Olyan közel!",
        "h5": "Ne állj meg most!",
        "h6": "Még egy kör?",
        "h7": "Tartsd a sorozatot!",
        "sub": "Innen folytatod?",
        "cont": "Folytatás (+%d élet)",
        "pr": "+%d élet — pont onnan folytatod, ahol abbahagytad",
        "pp": "Nem veszíted el a haladást",
        "ur": "Gyorsan — őrizd a haladást!",
        "ad": "Reklámmentesen Premium-mal",
        "cp": "Folytatás Premium-mal",
    },
    "id": {
        "h1": "Hampir berhasil! 🚀",
        "h2": "Lanjut?",
        "h3": "Tinggal satu langkah!",
        "h4": "Sangat dekat!",
        "h5": "Jangan berhenti sekarang!",
        "h6": "Satu putaran lagi?",
        "h7": "Pertahankan streak!",
        "sub": "Lanjut dari sini?",
        "cont": "Lanjut (+%d nyawa)",
        "pr": "+%d nyawa — lanjut persis dari posisi terakhir",
        "pp": "Progresmu tidak hilang",
        "ur": "Cepat — jaga progresmu!",
        "ad": "Tanpa iklan dengan Premium",
        "cp": "Lanjut dengan Premium",
    },
    "ro": {
        "h1": "Aproape ai reușit! 🚀",
        "h2": "Continuăm?",
        "h3": "A mai rămas un pas!",
        "h4": "Atât de aproape!",
        "h5": "Nu te opri acum!",
        "h6": "Încă o rundă?",
        "h7": "Păstrează seria!",
        "sub": "Continuăm de aici?",
        "cont": "Continuă (+%d vieți)",
        "pr": "+%d vieți — continui exact de unde ai rămas",
        "pp": "Nu îți pierzi progresul",
        "ur": "Repede — păstrează progresul!",
        "ad": "Fără reclame cu Premium",
        "cp": "Continuă cu Premium",
    },
    "sv": {
        "h1": "Du är nästan i mål! 🚀",
        "h2": "Ska vi fortsätta?",
        "h3": "Ett steg kvar!",
        "h4": "Så nära!",
        "h5": "Sluta inte nu!",
        "h6": "En runda till?",
        "h7": "Behåll sviten!",
        "sub": "Fortsätt härifrån?",
        "cont": "Fortsätt (+%d liv)",
        "pr": "+%d liv — du fortsätter där du slutade",
        "pp": "Du tappar inte framstegen",
        "ur": "Skynda dig — behåll framstegen!",
        "ad": "Reklamfritt med Premium",
        "cp": "Fortsätt med Premium",
    },
    "ta": {
        "h1": "கிட்டத்தட்ட முடிந்தது! 🚀",
        "h2": "தொடரலாமா?",
        "h3": "கடைசி படி மட்டும்!",
        "h4": "அவ்வளவு அருகில்!",
        "h5": "இப்போது நிற்காதே!",
        "h6": "மற்றொரு சுற்று?",
        "h7": "தொடர்ச்சியைக் காப்பாற்று!",
        "sub": "இங்கிருந்து தொடரலாமா?",
        "cont": "தொடர் (+%d உயிர்கள்)",
        "pr": "+%d உயிர்கள் — நிறுத்திய இடத்திலிருந்தே",
        "pp": "முன்னேற்றம் போகாது",
        "ur": "விரைவாக — முன்னேற்றத்தைக் காப்பாற்று!",
        "ad": "Premium உடன் விளம்பரமில்லாமல்",
        "cp": "Premium உடன் தொடர்",
    },
    "te": {
        "h1": "దాదాపు అయిపోయింది! 🚀",
        "h2": "కొనసాగిద్దామా?",
        "h3": "చివరి అడుగు మిగిలింది!",
        "h4": "అంత దగ్గరగా!",
        "h5": "ఇప్పుడు ఆగవద్దు!",
        "h6": "మరో రౌండ్?",
        "h7": "స్ట్రీక్ కాపాడు!",
        "sub": "ఇక్కడ నుంచి కొనసాగిద్దామా?",
        "cont": "కొనసాగించు (+%d ప్రాణాలు)",
        "pr": "+%d ప్రాణాలు — ఆగిన చోట నుంచే",
        "pp": "ప్రగతి పోదు",
        "ur": "త్వరగా — ప్రగతిని కాపాడు!",
        "ad": "Premium తో ప్రకటనలు లేకుండా",
        "cp": "Premium తో కొనసాగించు",
    },
    "th": {
        "h1": "ใกล้แล้ว! 🚀",
        "h2": "เล่นต่อไหม?",
        "h3": "เหลืออีกก้าวเดียว!",
        "h4": "ใกล้มาก!",
        "h5": "อย่าหยุดตอนนี้!",
        "h6": "อีกรอบไหม?",
        "h7": "รักษาสถิติต่อ!",
        "sub": "เล่นต่อจากตรงนี้?",
        "cont": "เล่นต่อ (+%d ชีวิต)",
        "pr": "+%d ชีวิต — เริ่มต่อจากจุดที่ค้างไว้",
        "pp": "ความคืบหน้าไม่หาย",
        "ur": "เร็วเข้า — อย่าเสียความคืบหน้า!",
        "ad": "ไม่มีโฆษณากับ Premium",
        "cp": "เล่นต่อด้วย Premium",
    },
    "tr": {
        "h1": "Neredeyse başardın! 🚀",
        "h2": "Devam edelim mi?",
        "h3": "Son bir adım!",
        "h4": "Çok yakınsın!",
        "h5": "Şimdi durma!",
        "h6": "Bir tur daha?",
        "h7": "Seriyi koru!",
        "sub": "Buradan devam?",
        "cont": "Devam et (+%d can)",
        "pr": "+%d can — kaldığın yerden devam",
        "pp": "İlerlemen kaybolmaz",
        "ur": "Çabuk — ilerlemeyi koru!",
        "ad": "Premium ile reklamsız",
        "cp": "Premium ile devam et",
    },
    "vi": {
        "h1": "Sắp xong rồi! 🚀",
        "h2": "Tiếp tục nhé?",
        "h3": "Còn một bước nữa!",
        "h4": "Rất gần rồi!",
        "h5": "Đừng dừng lại!",
        "h6": "Thêm một vòng?",
        "h7": "Giữ chuỗi thắng!",
        "sub": "Tiếp tục từ đây?",
        "cont": "Tiếp tục (+%d mạng)",
        "pr": "+%d mạng — tiếp tục đúng chỗ bạn dừng",
        "pp": "Bạn không mất tiến trình",
        "ur": "Nhanh lên — giữ tiến trình!",
        "ad": "Không quảng cáo với Premium",
        "cp": "Tiếp tục với Premium",
    },
}


def patch_file(path: Path) -> bool:
    raw = path.read_text(encoding="utf-8")
    if CHECK in raw:
        return False
    if MARKER not in raw:
        print(f"SKIP (no marker): {path}")
        return False
    m = re.search(re.escape(MARKER) + r" = [^;]+;\n", raw)
    if not m:
        print(f"SKIP (regex): {path}")
        return False
    insert_at = m.end()
    folder = path.parent.name.replace(".lproj", "")
    if folder == "en":
        return False
    if folder not in TRANSLATIONS:
        print(f"SKIP (no dict): {path}")
        return False
    new_block = block_for(folder)
    path.write_text(raw[:insert_at] + new_block + raw[insert_at:], encoding="utf-8")
    return True


def main() -> None:
    n = 0
    for lproj in sorted(RES.glob("*.lproj")):
        f = lproj / "Localizable.strings"
        if not f.is_file():
            continue
        if patch_file(f):
            n += 1
            print(f"Patched: {f.relative_to(ROOT)}")
    print(f"Done. Patched {n} files.")


if __name__ == "__main__":
    main()
