#!/usr/bin/env python3
"""Generate localized App Store update copy for version 8.0 (80)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Four matching release highlights and a localized promotional sentence.
COPY = {
'en-US': ('A refreshed quiz screen with clearer answers and animated lives.|Redesigned Statistics, Leagues and Profile screens.|Improved iPad layouts and cards that adapt to their content.|Region and difficulty changes now save when you close quick settings.', 'Explore world flags with a refreshed quiz, clearer statistics and improved iPad layouts. Play, learn and climb the leagues!'),
'ru': ('Обновлённый игровой экран: понятные варианты ответов и анимация жизней.|Новый дизайн страниц «Статистика», «Лиги» и «Профиль».|Улучшенная компоновка на iPad: карточки подстраиваются под содержимое.|Регион и сложность сохраняются при закрытии быстрых настроек.', 'Изучайте флаги мира: обновлённый квиз, наглядная статистика и удобные экраны на iPad. Играйте, учитесь и поднимайтесь по лигам!'),
'uk': ('Оновлений ігровий екран: зрозумілі варіанти відповідей та анімація життів.|Новий дизайн сторінок «Статистика», «Ліги» та «Профіль».|Покращене компонування на iPad: картки підлаштовуються під вміст.|Регіон і складність зберігаються після закриття швидких налаштувань.', 'Вивчайте прапори світу: оновлений квіз, наочна статистика та зручні екрани на iPad. Грайте, навчайтеся й піднімайтеся лігами!'),
'de-DE': ('Überarbeiteter Quizbildschirm mit übersichtlichen Antworten und animierten Leben.|Neues Design für Statistik, Ligen und Profil.|Verbesserte iPad-Layouts und Karten, die sich ihrem Inhalt anpassen.|Region und Schwierigkeitsgrad werden beim Schließen der Schnelleinstellungen gespeichert.', 'Entdecke die Flaggen der Welt mit überarbeitetem Quiz, klarer Statistik und verbesserten iPad-Layouts. Spiele, lerne und steige in den Ligen auf!'),
'fr-FR': ('Un écran de quiz repensé, avec des réponses plus lisibles et des vies animées.|Nouveau design des écrans Statistiques, Ligues et Profil.|Une mise en page améliorée sur iPad et des cartes adaptées au contenu.|La région et la difficulté sont enregistrées à la fermeture des réglages rapides.', 'Découvrez les drapeaux du monde : quiz repensé, statistiques claires et affichage amélioré sur iPad. Jouez, apprenez et progressez dans les ligues !'),
'es-ES': ('Pantalla del quiz renovada, con respuestas más claras y vidas animadas.|Nuevo diseño de Estadísticas, Ligas y Perfil.|Diseños mejorados para iPad y tarjetas que se adaptan al contenido.|La región y la dificultad se guardan al cerrar los ajustes rápidos.', 'Descubre las banderas del mundo con un quiz renovado, estadísticas claras y mejoras para iPad. ¡Juega, aprende y sube de liga!'),
'it': ('Schermata del quiz rinnovata con risposte più chiare e vite animate.|Nuovo design per Statistiche, Leghe e Profilo.|Layout migliorati su iPad e schede che si adattano al contenuto.|Regione e difficoltà vengono salvate alla chiusura delle impostazioni rapide.', 'Scopri le bandiere del mondo con un quiz rinnovato, statistiche chiare e layout migliorati su iPad. Gioca, impara e sali di lega!'),
'pt-BR': ('Tela do quiz renovada, com respostas mais claras e vidas animadas.|Novo design das telas Estatísticas, Ligas e Perfil.|Layouts aprimorados no iPad e cartões que se ajustam ao conteúdo.|Região e dificuldade são salvas ao fechar os ajustes rápidos.', 'Explore as bandeiras do mundo com um quiz renovado, estatísticas claras e melhorias no iPad. Jogue, aprenda e avance nas ligas!'),
'pl': ('Odświeżony ekran quizu z czytelniejszymi odpowiedziami i animacją żyć.|Nowy wygląd ekranów Statystyki, Ligi i Profil.|Ulepszony układ na iPadzie i karty dopasowane do treści.|Region i poziom trudności zapisują się po zamknięciu szybkich ustawień.', 'Poznawaj flagi świata dzięki odświeżonemu quizowi, czytelnym statystykom i ulepszeniom na iPadzie. Graj, ucz się i awansuj w ligach!'),
'nl-NL': ('Vernieuwd quizscherm met duidelijkere antwoorden en geanimeerde levens.|Nieuw ontwerp voor Statistieken, Competities en Profiel.|Verbeterde iPad-indeling en kaarten die zich aan de inhoud aanpassen.|Regio en moeilijkheid worden opgeslagen als je de snelle instellingen sluit.', 'Ontdek wereldvlaggen met een vernieuwde quiz, duidelijke statistieken en een betere iPad-indeling. Speel, leer en stijg in de competities!'),
'ca': ('Pantalla del qüestionari renovada, amb respostes més clares i vides animades.|Nou disseny de les pantalles Estadístiques, Lligues i Perfil.|Millores de disseny a l’iPad i targetes que s’adapten al contingut.|La regió i la dificultat es desen en tancar els ajustos ràpids.', 'Descobreix les banderes del món amb un qüestionari renovat, estadístiques clares i millores a l’iPad. Juga, aprèn i puja de lliga!'),
'cs': ('Obnovená obrazovka kvízu s přehlednějšími odpověďmi a animovanými životy.|Nový vzhled obrazovek Statistiky, Ligy a Profil.|Lepší rozložení na iPadu a karty přizpůsobené obsahu.|Region a obtížnost se ukládají při zavření rychlého nastavení.', 'Poznávejte vlajky světa v novém kvízu s přehlednými statistikami a lepším rozložením na iPadu. Hrajte, učte se a postupujte ligami!'),
'el': ('Ανανεωμένη οθόνη κουίζ με πιο ευανάγνωστες απαντήσεις και κινούμενες ζωές.|Νέος σχεδιασμός για Στατιστικά, Πρωταθλήματα και Προφίλ.|Βελτιωμένη διάταξη στο iPad και κάρτες που προσαρμόζονται στο περιεχόμενο.|Η περιοχή και η δυσκολία αποθηκεύονται όταν κλείνετε τις γρήγορες ρυθμίσεις.', 'Μάθετε τις σημαίες του κόσμου με ανανεωμένο κουίζ, ξεκάθαρα στατιστικά και καλύτερη διάταξη στο iPad. Παίξτε και ανεβείτε στα πρωταθλήματα!'),
'hu': ('Megújult kvízképernyő áttekinthetőbb válaszokkal és animált életekkel.|Új megjelenést kapott a Statisztika, a Ligák és a Profil.|Jobb iPad-elrendezés, a tartalomhoz igazodó kártyákkal.|A régió és a nehézség a gyorsbeállítások bezárásakor mentésre kerül.', 'Fedezd fel a világ zászlóit megújult kvízzel, áttekinthető statisztikákkal és jobb iPad-elrendezéssel. Játssz, tanulj és lépj feljebb a ligákban!'),
'ro': ('Ecran de quiz reînnoit, cu răspunsuri mai clare și vieți animate.|Design nou pentru Statistică, Ligi și Profil.|Aspect îmbunătățit pe iPad și carduri adaptate conținutului.|Regiunea și dificultatea se salvează la închiderea setărilor rapide.', 'Descoperă steagurile lumii cu un quiz reînnoit, statistici clare și un aspect îmbunătățit pe iPad. Joacă, învață și avansează în ligi!'),
'sv': ('Förnyad quizvy med tydligare svar och animerade liv.|Ny design för Statistik, Ligor och Profil.|Förbättrad iPad-layout och kort som anpassas efter innehållet.|Region och svårighetsgrad sparas när du stänger snabbinställningarna.', 'Lär dig världens flaggor med ett förnyat quiz, tydlig statistik och bättre iPad-layout. Spela, lär dig och klättra i ligorna!'),
'id': ('Layar kuis diperbarui dengan jawaban lebih jelas dan nyawa beranimasi.|Desain baru untuk Statistik, Liga, dan Profil.|Tata letak iPad ditingkatkan dengan kartu yang menyesuaikan isi.|Wilayah dan tingkat kesulitan disimpan saat pengaturan cepat ditutup.', 'Pelajari bendera dunia dengan kuis baru, statistik yang jelas, dan tampilan iPad yang lebih baik. Bermain, belajar, dan naik liga!'),
'tr': ('Daha net yanıtlar ve animasyonlu canlarla yenilenen bilgi yarışması ekranı.|İstatistikler, Ligler ve Profil ekranları için yeni tasarım.|iPad düzeni iyileştirildi; kartlar artık içeriğe uyum sağlıyor.|Bölge ve zorluk, hızlı ayarlar kapatıldığında kaydediliyor.', 'Yenilenen bilgi yarışması, anlaşılır istatistikler ve iyileştirilmiş iPad düzeniyle dünya bayraklarını keşfet. Oyna, öğren ve liglerde yüksel!'),
'vi': ('Màn hình đố vui mới với đáp án rõ ràng hơn và hiệu ứng mạng chơi.|Thiết kế mới cho Thống kê, Giải đấu và Hồ sơ.|Cải thiện bố cục iPad và thẻ tự điều chỉnh theo nội dung.|Khu vực và độ khó được lưu khi đóng cài đặt nhanh.', 'Khám phá cờ thế giới với màn đố vui mới, thống kê rõ ràng và bố cục iPad cải tiến. Chơi, học và thăng hạng!'),
'ja': ('クイズ画面を刷新。回答を見やすくし、ライフのアニメーションを改善しました。|統計、リーグ、プロフィール画面のデザインを更新しました。|iPadのレイアウトを改善し、カードが内容に合わせて表示されるようになりました。|クイック設定を閉じると、地域と難易度が保存されます。', '新しくなったクイズ、見やすい統計、使いやすいiPad画面で世界の国旗を学ぼう。遊びながら知識を深め、リーグの上位を目指そう！'),
'ko': ('더 명확한 답변과 생명 애니메이션으로 퀴즈 화면을 새롭게 개선했습니다.|통계, 리그, 프로필 화면의 디자인을 새롭게 바꿨습니다.|iPad 레이아웃을 개선하고 카드가 내용에 맞춰 표시되도록 했습니다.|빠른 설정을 닫으면 지역과 난이도가 저장됩니다.', '새로워진 퀴즈, 보기 쉬운 통계, 개선된 iPad 화면으로 세계 국기를 배워 보세요. 즐기며 배우고 리그 순위를 올려 보세요!'),
'zh-Hans': ('焕新的答题界面：选项更清晰，生命动画更生动。|重新设计了统计、联赛和个人资料页面。|优化了 iPad 布局，卡片高度随内容调整。|关闭快捷设置时，自动保存地区和难度。', '通过焕新的答题界面、清晰的统计和优化的 iPad 布局，探索世界国旗。边玩边学，向更高联赛迈进！'),
'zh-Hant': ('煥新的答題介面：選項更清晰，生命動畫更生動。|重新設計了統計、聯賽和個人資料頁面。|改善了 iPad 版面配置，卡片高度隨內容調整。|關閉快速設定時，自動儲存地區和難度。', '透過煥新的答題介面、清晰的統計和改善的 iPad 版面配置，探索世界國旗。邊玩邊學，邁向更高聯賽！'),
'ar-SA': ('واجهة اختبار مجددة بإجابات أوضح وحركات للأرواح.|تصميم جديد لشاشات الإحصاءات والدوريات والملف الشخصي.|تحسين تخطيط iPad وبطاقات تتكيف مع المحتوى.|حفظ المنطقة ومستوى الصعوبة عند إغلاق الإعدادات السريعة.', 'اكتشف أعلام العالم باختبار متجدد وإحصاءات واضحة وتجربة أفضل على iPad. العب وتعلم وارتقِ في الدوريات!'),
'hi': ('ज़्यादा स्पष्ट उत्तरों और जीवन के ऐनिमेशन के साथ नया क्विज़ स्क्रीन।|आँकड़े, लीग और प्रोफ़ाइल स्क्रीन का नया डिज़ाइन।|iPad पर बेहतर लेआउट और सामग्री के अनुसार आकार बदलने वाले कार्ड।|त्वरित सेटिंग बंद करने पर क्षेत्र और कठिनाई सहेजे जाते हैं।', 'नए क्विज़, स्पष्ट आँकड़ों और बेहतर iPad लेआउट के साथ दुनिया के झंडे सीखें। खेलें, सीखें और लीग में आगे बढ़ें!'),
'th': ('หน้าควิซโฉมใหม่ พร้อมตัวเลือกคำตอบที่อ่านง่ายขึ้นและแอนิเมชันชีวิต|ดีไซน์ใหม่สำหรับหน้าสถิติ ลีก และโปรไฟล์|ปรับปรุงเลย์เอาต์บน iPad และการ์ดที่ปรับขนาดตามเนื้อหา|บันทึกภูมิภาคและระดับความยากเมื่อปิดการตั้งค่าด่วน', 'เรียนรู้ธงทั่วโลกด้วยควิซโฉมใหม่ สถิติที่ชัดเจน และเลย์เอาต์ iPad ที่ดีขึ้น เล่น เรียนรู้ และไต่อันดับลีก!'),
}

if __name__ == '__main__':
    meta = ROOT / 'fastlane/metadata'
    assert set(COPY) == {p.name for p in meta.iterdir() if p.is_dir()}
    for locale, (notes, promo) in COPY.items():
        text = '8.0\n\n' + '\n'.join('• ' + line for line in notes.split('|')) + '\n'
        assert len(text) <= 4000 and len(promo) <= 170, (locale, len(promo))
        for filename in ('release_notes.txt', 'whats_new.txt'):
            (meta / locale / filename).write_text(text)
        (meta / locale / 'promotional_text.txt').write_text(promo + '\n')
    print(f'Prepared and validated {len(COPY)} locales for version 8.0.')
